import android.content.Context;
import android.content.SharedPreferences;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;
import pfm.android.AndroidRuntime;

/** Persistent per-fixture facts plus the v39 calibrated coherent match flow. */
public final class pfmLeagueMatchArchive34 {
    private static final String PREFS="pfm_match_archive_v34";
    private pfmLeagueMatchArchive34() {}
    private static SharedPreferences prefs(){return AndroidRuntime.context().getSharedPreferences(PREFS,Context.MODE_PRIVATE);}
    private static Field f(Class<?> c,String n,Class<?> t)throws Exception{for(Field x:c.getDeclaredFields())if(x.getName().equals(n)&&x.getType()==t){x.setAccessible(true);return x;}throw new NoSuchFieldException(n);}
    private static int ub(Object o,String n){try{return f(o.getClass(),n,Byte.TYPE).getByte(o)&255;}catch(Throwable x){return 0;}}
    private static String clean(String s){return s==null?"?":s.replace('\t',' ').replace('\n',' ').trim();}
    private static String playerName(ci p){try{return clean(pfmPlayerName60.name(p));}catch(Throwable x){return "Player";}}
    private static String teamName(dw t){try{return clean(pfmAccess50.name(t));}catch(Throwable x){return "Team";}}
    private static String pos(ci p){int x=ub(p,"b");return x==0?"GK":x==1?"DEF":x==2?"MID":x==3?"FW":"?";}
    private static ci player(int id){try{ci[] a=(ci[])f(cp.class,"a",ci[].class).get(null);return id>=0&&id<a.length?a[id]:null;}catch(Throwable x){return null;}}
    private static int id(ci p){try{ci[] a=(ci[])f(cp.class,"a",ci[].class).get(null);for(int i=0;i<a.length;i++)if(a[i]==p)return i;}catch(Throwable ignored){}return -1;}
    private static int teamId(dw t){return ub(t,"n");}
    private static int roundOne(){try{return pfmMatchPost35.completedRoundOne();}catch(Throwable x){return 1;}}
    private static String prefix(int round){int season=0,slot=0;try{season=pfm2.getSeason();slot=pfm2.getSlot();}catch(Throwable ignored){}return "m_"+slot+'_'+season+'_'+round+'_';}
    private static String key(int round,dw h,dw a){return prefix(round)+teamId(h)+'_'+teamId(a);}
    private static int minuteInt(Object x){String s=String.valueOf(x).trim();StringBuilder b=new StringBuilder();for(int i=0;i<s.length();i++)if(Character.isDigit(s.charAt(i)))b.append(s.charAt(i));try{return Math.max(1,Math.min(90,Integer.parseInt(b.toString())));}catch(Throwable ignored){return 45;}}
    private static String minute(Object x){return String.valueOf(minuteInt(x));}
    private static int goalsFor(Vector v,ci p){int n=0;for(int i=0;i+1<v.size();i+=2)if(v.elementAt(i)==p)n++;return n;}
    private static String goalMinutes(Vector v,ci p){StringBuilder b=new StringBuilder();for(int i=0;i+1<v.size();i+=2)if(v.elementAt(i)==p){if(b.length()>0)b.append(',');b.append(minute(v.elementAt(i+1)));}return b.toString();}
    private static int points(int gf,int ga){return gf>ga?3:gf==ga?1:0;}
    private static int hash(int x){x^=x>>>16;x*=0x7feb352d;x^=x>>>15;x*=0x846ca68b;x^=x>>>16;return x&0x7fffffff;}
    private static int mod(int x,int n){return n<=0?0:hash(x)%n;}
    private static int clamp(int x,int lo,int hi){return Math.max(lo,Math.min(hi,x));}
    private static int spread(int seed,int radius){return mod(seed,2*radius+1)-radius;}
    private static String[] grow(String[] p,int n){if(p.length>=n)return p;String[] x=new String[n];System.arraycopy(p,0,x,0,p.length);for(int i=p.length;i<n;i++)x[i]="";return x;}

    /** side,index,id,number,name,pos,starter,minutes */
    private static ArrayList<String[]> participants(dw team,int side,int round){ArrayList<String[]> out=new ArrayList<String[]>();int count=0;try{count=Math.min(25,pfmRosterAccess50.count(team));}catch(Throwable ignored){}for(int i=0;i<count;i++)try{ci p=cp.a(team,i);if(p==null)continue;int mins=pfmCondition60.minutesForRosterIndex(team,i,round);boolean starter=i<11;if(!starter&&mins<=0)continue;if(starter&&mins<=0)mins=90;out.add(new String[]{String.valueOf(side),String.valueOf(i),String.valueOf(id(p)),String.valueOf(ub(p,"f")),playerName(p),pos(p),starter?"1":"0",String.valueOf(mins)});}catch(Throwable ignored){}return out;}
    private static int startMinute(String[] p){try{return "1".equals(p[5])?1:Math.max(1,91-Integer.parseInt(p[6]));}catch(Throwable ignored){return 1;}}
    private static int endMinute(String[] p){try{return "1".equals(p[5])?Math.min(90,Integer.parseInt(p[6])):90;}catch(Throwable ignored){return 90;}}
    private static boolean activeAt(String[] p,int minute){return minute>=startMinute(p)&&minute<=endMinute(p);}
    private static boolean rawActiveAt(String[] p,int minute){try{int mins=Integer.parseInt(p[7]);return "1".equals(p[6])?minute<=mins:minute>=Math.max(1,91-mins);}catch(Throwable ignored){return false;}}
    private static int eventMax(String[] p){int max=startMinute(p);for(int col=8;col<=12&&col<p.length;col++)for(String s:p[col].split(","))try{max=Math.max(max,Integer.parseInt(s));}catch(Throwable ignored){}return max;}
    private static int weight(String[] p,int kind){String po=p[4];ci x=null;try{x=player(Integer.parseInt(p[10]));}catch(Throwable ignored){}int quality=x==null?70:(ub(x,"c")+ub(x,"d")+ub(x,"e"))/3;if(kind==0){if("GK".equals(po))return 0;return ("DEF".equals(po)?7:"MID".equals(po)?25:65)+quality/12;}if(kind==1){if("GK".equals(po))return 0;return ("DEF".equals(po)?16:"MID".equals(po)?50:34)+quality/15;}if("GK".equals(po))return 0;return ("DEF".equals(po)?44:"MID".equals(po)?39:27)+quality/20;}
    private static String[] pick(ArrayList<String[]> ps,int side,int minute,int excluded,int kind,int seed,boolean fullMatch){int total=0;for(String[] p:ps)try{if(!"P".equals(p[0])||Integer.parseInt(p[1])!=side||Integer.parseInt(p[10])==excluded||!activeAt(p,minute)||(fullMatch&&Integer.parseInt(p[6])<85))continue;total+=weight(p,kind);}catch(Throwable ignored){}if(total<=0&&fullMatch)return pick(ps,side,minute,excluded,kind,seed,false);if(total<=0)return null;int roll=mod(seed,total);for(String[] p:ps)try{if(!"P".equals(p[0])||Integer.parseInt(p[1])!=side||Integer.parseInt(p[10])==excluded||!activeAt(p,minute)||(fullMatch&&Integer.parseInt(p[6])<85))continue;roll-=weight(p,kind);if(roll<0)return p;}catch(Throwable ignored){}return null;}
    private static void normalizeGoals(Vector goals,ArrayList<String[]> rows,int side,int round,int seed){for(int i=0;i+1<goals.size();i+=2)try{ci scorer=(ci)goals.elementAt(i);int pid=id(scorer),m=minuteInt(goals.elementAt(i+1));String[] current=null;for(String[] p:rows)if(Integer.parseInt(p[2])==pid){current=p;break;}boolean rareKeeper=current!=null&&"GK".equals(current[5])&&mod(seed+round*977+i*131,20)==0;if(current!=null&&rawActiveAt(current,m)&&(!"GK".equals(current[5])||rareKeeper))continue;ArrayList<String[]> archiveRows=new ArrayList<String[]>();for(String[] p:rows)archiveRows.add(new String[]{"P",String.valueOf(side),p[3],p[4],p[5],p[6],p[7],"65","","",p[2],"",""});String[] replacement=pick(archiveRows,side,m,-1,0,seed+round*977+i*131,false);if(replacement!=null){ci chosen=player(Integer.parseInt(replacement[10]));if(chosen!=null)goals.setElementAt(chosen,i);}}catch(Throwable ignored){}}
    private static void appendTeam(StringBuilder out,ArrayList<String[]> ps,Vector goals,int gf,int ga,int round){for(String[] x:ps)try{int pid=Integer.parseInt(x[2]);ci p=player(pid);int pg=goalsFor(goals,p),rating=pfmPatch36.buildRating(p,points(gf,ga),gf,ga,pg,pid,round);out.append("P\t").append(x[0]).append('\t').append(x[3]).append('\t').append(x[4]).append('\t').append(x[5]).append('\t').append(x[6]).append('\t').append(x[7]).append('\t').append(rating).append('\t').append(goalMinutes(goals,p)).append("\t\t").append(pid).append("\t\t\n");}catch(Throwable ignored){}}
    private static void appendSubs(StringBuilder out,ArrayList<String[]> ps,int side){ArrayList<String[]> outs=new ArrayList<String[]>(),ins=new ArrayList<String[]>();for(String[] p:ps){int m=Integer.parseInt(p[7]);if("1".equals(p[6])&&m<90)outs.add(p);if("0".equals(p[6])&&m>0)ins.add(p);}boolean[] used=new boolean[ins.size()];for(String[] o:outs){int om=Integer.parseInt(o[7]),best=-1;for(int i=0;i<ins.size();i++)if(!used[i]&&ins.get(i)[5].equals(o[5])&&90-Integer.parseInt(ins.get(i)[7])==om){best=i;break;}if(best<0)for(int i=0;i<ins.size();i++)if(!used[i]&&90-Integer.parseInt(ins.get(i)[7])==om){best=i;break;}if(best>=0){used[best]=true;String[] in=ins.get(best);out.append("S\t").append(side).append('\t').append(om).append('\t').append(o[4]).append('\t').append(in[4]).append('\t').append(o[2]).append('\t').append(in[2]).append('\n');}}}
    private static int strength(dw t){int sum=0,n=0;try{for(int i=0;i<11;i++){ci p=cp.a(t,i);if(p!=null){sum+=ub(p,"c")+ub(p,"d")+ub(p,"e");n+=3;}}}catch(Throwable ignored){}return n==0?70:sum/n;}

    private static int shotFloor(int goals,int seed){if(mod(seed,1000)<15)return Math.max(1,goals);return goals==0?4:goals*2+2;}

    /** One flow still tells a coherent story, but score and tactical noise now constrain its tails. */
    private static void appendStats(StringBuilder out,dw h,dw a,int hg,int ag,int round){int hs=strength(h),as=strength(a),season=0;try{season=pfm2.getSeason();}catch(Throwable ignored){}int seed=teamId(h)*1009+teamId(a)*719+round*313+season*104729;int control=(hs-as)/2+3+spread(seed+1,15)+spread(seed+2,7);int hp=clamp(50+control,28,72),ap=100-hp;int tempo=spread(seed+3,3);int hraw=11+(hp-50)/5+(hs-70)/10+tempo+spread(seed+4,5)+spread(seed+14,3);int araw=11+(ap-50)/5+(as-70)/10+tempo+spread(seed+5,5)+spread(seed+15,3);int hsh=clamp(Math.max(shotFloor(hg,seed+16),hraw),1,26),ash=clamp(Math.max(shotFloor(ag,seed+17),araw),1,26);int hstRaw=hg+(hsh-hg)*(22+mod(seed+6,23))/100+spread(seed+24,2),astRaw=ag+(ash-ag)*(22+mod(seed+7,23))/100+spread(seed+25,2);if(hg==0&&mod(seed+26,20)==0)hstRaw=0;if(ag==0&&mod(seed+27,20)==0)astRaw=0;int hst=clamp(hstRaw,hg,hsh),ast=clamp(astRaw,ag,ash);int hc=clamp(2+hsh/4+Math.max(0,hp-50)/15+spread(seed+8,2)+spread(seed+18,1),0,14),ac=clamp(2+ash/4+Math.max(0,ap-50)/15+spread(seed+9,2)+spread(seed+19,1),0,14);int htail=mod(seed+20,20)==0?5+mod(seed+21,6):0,atail=mod(seed+22,20)==0?5+mod(seed+23,6):0;int hf=clamp(13+(50-hp)/12+spread(seed+10,8)+htail,4,30),af=clamp(13+(50-ap)/12+spread(seed+11,8)+atail,4,30);int ho=clamp(hsh/10+mod(seed+12,4),0,7),ao=clamp(ash/10+mod(seed+13,4),0,7);out.append("M\t").append(hp).append('\t').append(ap).append('\t').append(hsh).append('\t').append(ash).append('\t').append(hst).append('\t').append(ast).append('\t').append(hc).append('\t').append(ac).append('\t').append(hf).append('\t').append(af).append('\t').append(ho).append('\t').append(ao).append("\t0\t0\t0\t0\n");}

    /** Preserve the result, but repair impossible scorers before the stock ledgers consume it. */
    public static void finish(dw home,dw away,Vector[] events){int round=roundOne();ArrayList<String[]> hp=participants(home,0,round),ap=participants(away,1,round);try{normalizeGoals(events[0],hp,0,round,teamId(home)*1709+teamId(away)*1013);normalizeGoals(events[1],ap,1,round,teamId(away)*1709+teamId(home)*1013);}catch(Throwable ignored){}try{Method m=ca.class.getDeclaredMethod("a",dw.class,dw.class,Vector[].class);m.setAccessible(true);m.invoke(null,home,away,events);}catch(Throwable fatal){return;}try{int hg=events[0].size()/2,ag=events[1].size()/2;StringBuilder out=new StringBuilder();out.append("H\t").append(teamName(home)).append('\t').append(teamName(away)).append('\t').append(hg).append('\t').append(ag).append('\n');for(int side=0;side<2;side++)for(int i=0;i+1<events[side].size();i+=2){ci scorer=(ci)events[side].elementAt(i);out.append("G\t").append(side).append('\t').append(minute(events[side].elementAt(i+1))).append('\t').append(playerName(scorer)).append("\t\t").append(id(scorer)).append('\n');}appendSubs(out,hp,0);appendSubs(out,ap,1);appendStats(out,home,away,hg,ag,round);appendTeam(out,hp,events[0],hg,ag,round);appendTeam(out,ap,events[1],ag,hg,round);prefs().edit().putString(key(round,home,away),out.toString()).commit();}catch(Throwable ignored){}}

    private static byte[] bytes(Class<?> c,String name){try{byte[] b=(byte[])f(c,name,byte[].class).get(null);return b==null?new byte[0]:(byte[])b.clone();}catch(Throwable x){return new byte[0];}}
    private static byte[] liveBytes(Class<?> c,String name){try{return (byte[])f(c,name,byte[].class).get(null);}catch(Throwable x){return new byte[0];}}
    private static void save(Class<?> c){try{Method m=c.getDeclaredMethod("save");m.setAccessible(true);m.invoke(null);}catch(Throwable ignored){}}
    public static byte[] assistSnapshot(){try{pfmContrib80.assists(0);}catch(Throwable ignored){}return bytes(pfmContrib80.class,"assists");}
    public static byte[] yellowSnapshot(){try{pfmDiscipline70.roundsOut(0);}catch(Throwable ignored){}return bytes(pfmDiscipline70.class,"yellow");}
    public static byte[] redSnapshot(){try{pfmDiscipline70.roundsOut(0);}catch(Throwable ignored){}return bytes(pfmDiscipline70.class,"red");}
    public static byte[] suspensionSnapshot(){try{pfmDiscipline70.roundsOut(0);}catch(Throwable ignored){}return bytes(pfmDiscipline70.class,"suspension");}
    private static int delta(byte[] a,byte[] b,int id){return id>=0&&id<b.length?Math.max(0,(b[id]&255)-(id<a.length?(a[id]&255):0)):0;}
    private static ArrayList<String[]> parse(String raw){ArrayList<String[]> x=new ArrayList<String[]>();for(String s:raw.split("\n",-1))x.add(s.split("\t",-1));return x;}
    private static String serialize(ArrayList<String[]> ps){StringBuilder b=new StringBuilder();for(String[] p:ps){for(int i=0;i<p.length;i++){if(i>0)b.append('\t');b.append(p[i]);}b.append('\n');}return b.toString();}
    private static int clampRating(int x){return clamp(x,40,100);}
    private static int rate(String[] p,int change){try{int old=Integer.parseInt(p[7]),now=clampRating(old+change);p[7]=String.valueOf(now);return now-old;}catch(Throwable ignored){return 0;}}
    private static void addMinute(String[] p,int col,int m){String s=String.valueOf(m);p[col]=p[col].length()==0?s:p[col]+","+s;}
    private static String[] activeKeeper(ArrayList<String[]> ps,int side,int minute,int scorer){for(String[] p:ps)try{if("P".equals(p[0])&&Integer.parseInt(p[1])==side&&Integer.parseInt(p[10])!=scorer&&"GK".equals(p[4])&&activeAt(p,minute))return p;}catch(Throwable ignored){}return null;}

    /** Replace the stock roster-wide assist draw with a goal-minute eligible draw. */
    public static void applyAssists(byte[] before,byte[] after,int round){try{byte[] live=liveBytes(pfmContrib80.class,"assists");int[] stock=new int[Math.max(before.length,after.length)];for(int i=0;i<stock.length;i++){stock[i]=delta(before,after,i);if(stock[i]>0&&i<live.length)live[i]=(byte)(i<before.length?(before[i]&255):0);}SharedPreferences.Editor edit=prefs().edit();for(Map.Entry<String,?> e:prefs().getAll().entrySet()){if(!e.getKey().startsWith(prefix(round))||!(e.getValue() instanceof String))continue;ArrayList<String[]> ps=parse((String)e.getValue());for(int side=0;side<2;side++){int quota=0;ArrayList<String[]> goals=new ArrayList<String[]>();for(String[] p:ps)try{if("P".equals(p[0])&&Integer.parseInt(p[1])==side)quota+=stock[Integer.parseInt(p[10])];else if("G".equals(p[0])&&Integer.parseInt(p[1])==side)goals.add(p);}catch(Throwable ignored){}for(int gi=0;gi<goals.size()&&quota>0;gi++){String[] g=goals.get(gi);int scorer=Integer.parseInt(g[5]),m=Integer.parseInt(g[2]),draw=round*7919+side*997+gi*313+scorer*37+m*17;String[] chosen=mod(draw,600)==0?activeKeeper(ps,side,m,scorer):null;if(chosen==null)chosen=pick(ps,side,m,scorer,1,draw,false);if(chosen==null)continue;int pid=Integer.parseInt(chosen[10]);if(pid>=0&&pid<live.length&&(live[pid]&255)<255){live[pid]=(byte)((live[pid]&255)+1);g[4]=chosen[3];addMinute(chosen,9,m);int applied=rate(chosen,4);pfmRatingPost36.adjust(pid,applied);quota--;}}}edit.putString(e.getKey(),serialize(ps));}edit.commit();save(pfmContrib80.class);}catch(Throwable ignored){}}

    private static void moveOne(byte[] live,int from,int to){if(from==to||from<0||to<0||from>=live.length||to>=live.length)return;if((live[from]&255)>0)live[from]=(byte)((live[from]&255)-1);if((live[to]&255)<255)live[to]=(byte)((live[to]&255)+1);}
    private static int cardMinute(String[] p,int seed,boolean red){int lo=startMinute(p),hi=endMinute(p);if(!red){if("GK".equals(p[4]))lo=Math.max(lo,72);if(lo>hi)lo=hi;return lo+mod(seed,Math.max(1,hi-lo+1));}lo=Math.max(lo,eventMax(p));int roll=mod(seed,100),wanted;if(roll<8)wanted=12+mod(seed+1,18);else if(roll<30)wanted=30+mod(seed+2,20);else if(roll<68)wanted=50+mod(seed+3,20);else wanted=70+mod(seed+4,17);return clamp(wanted,Math.min(lo,hi),hi);}
    private static void redFlow(String[] m,int[] earliest){try{int hp=Integer.parseInt(m[1]),hs=Integer.parseInt(m[3]),as=Integer.parseInt(m[4]),hst=Integer.parseInt(m[5]),ast=Integer.parseInt(m[6]),hc=Integer.parseInt(m[7]),ac=Integer.parseInt(m[8]);int homeLoss=earliest[0]>0?clamp((90-earliest[0])/10,1,8):0,awayLoss=earliest[1]>0?clamp((90-earliest[1])/10,1,8):0,shift=awayLoss-homeLoss;hp=clamp(hp+shift,25,75);m[1]=String.valueOf(hp);m[2]=String.valueOf(100-hp);hs=clamp(hs+shift/2,hst,26);as=clamp(as-shift/2,ast,26);m[3]=String.valueOf(hs);m[4]=String.valueOf(as);m[5]=String.valueOf(clamp(hst,0,hs));m[6]=String.valueOf(clamp(ast,0,as));m[7]=String.valueOf(clamp(hc+shift/3,0,14));m[8]=String.valueOf(clamp(ac-shift/3,0,14));}catch(Throwable ignored){}}
    private static void disciplineFlow(String[] m,int[] counts){try{int hf=Integer.parseInt(m[9]),af=Integer.parseInt(m[10]);m[9]=String.valueOf(clamp(hf+(counts[0]-2)*2+counts[2]*3,4,30));m[10]=String.valueOf(clamp(af+(counts[1]-2)*2+counts[3]*3,4,30));}catch(Throwable ignored){}}

    /** A deliberately small keeper-only correction from the visible match flow. */
    private static void goalkeeperFlow(ArrayList<String[]> ps){try{String[] h=null,m=null;for(String[] p:ps){if("H".equals(p[0]))h=p;else if("M".equals(p[0]))m=p;}if(h==null||m==null||h.length<5||m.length<7)return;m=grow(m,18);if("1".equals(m[17]))return;m[17]="1";for(int side=0;side<2;side++){int faced=Integer.parseInt(m[side==0?6:5]),conceded=Integer.parseInt(h[side==0?4:3]),saves=Math.max(0,faced-conceded),delta=clamp(saves-3,-2,3);if(conceded==0)delta++;if(conceded>=3)delta--;delta=clamp(delta,-3,4);for(String[] p:ps)if("P".equals(p[0])&&Integer.parseInt(p[1])==side&&"GK".equals(p[4])&&"1".equals(p[5])){int applied=rate(p,delta);pfmRatingPost36.adjust(Integer.parseInt(p[10]),applied);break;}}for(int i=0;i<ps.size();i++)if("M".equals(ps.get(i)[0])){ps.set(i,m);break;}}catch(Throwable ignored){}}

    /** Give cards coherent owners/minutes; a red card closes the player's interval. */
    public static void applyCards(byte[] y0,byte[] y1,byte[] r0,byte[] r1,byte[] s0,byte[] s1,int round){try{byte[] yl=liveBytes(pfmDiscipline70.class,"yellow"),rl=liveBytes(pfmDiscipline70.class,"red"),sl=liveBytes(pfmDiscipline70.class,"suspension");SharedPreferences.Editor edit=prefs().edit();for(Map.Entry<String,?> e:prefs().getAll().entrySet()){if(!e.getKey().startsWith(prefix(round))||!(e.getValue() instanceof String))continue;ArrayList<String[]> ps=parse((String)e.getValue());int[] counts=new int[4],earliest={0,0};for(int i=0;i<ps.size();i++){String[] source=ps.get(i);if(source.length<11||!"P".equals(source[0]))continue;source=grow(source,13);ps.set(i,source);int side=Integer.parseInt(source[1]),pid=Integer.parseInt(source[10]),dy=delta(y0,y1,pid),dr=delta(r0,r1,pid);for(int n=0;n<dy;n++){String[] target=source;if("GK".equals(source[4])&&mod(pid*131+round*719+n*97,100)<88){String[] x=pick(ps,side,75,pid,2,pid*313+round*997+n,false);if(x!=null)target=x;}int tid=Integer.parseInt(target[10]);if(tid!=pid){moveOne(yl,pid,tid);if(pid<s0.length&&pid<s1.length&&tid<sl.length&&(s1[pid]&255)>(s0[pid]&255)){sl[pid]=(byte)(s0[pid]&255);if((yl[tid]&255)%5==0)sl[tid]=(byte)Math.max(sl[tid]&255,1);}}int cm=cardMinute(target,pid*131+round*719+n*97,false);addMinute(target,11,cm);counts[side]++;int applied=rate(target,-2);pfmRatingPost36.adjust(tid,applied);}for(int n=0;n<dr;n++){String[] target=source;if("GK".equals(source[4])||Integer.parseInt(source[6])<85){String[] x=pick(ps,side,60,pid,2,pid*173+round*977+n*101,true);if(x!=null)target=x;}int tid=Integer.parseInt(target[10]);if(tid!=pid){moveOne(rl,pid,tid);if(pid<s0.length&&pid<s1.length&&tid<sl.length){int ban=Math.max(1,(s1[pid]&255)-(s0[pid]&255));sl[pid]=(byte)(s0[pid]&255);sl[tid]=(byte)Math.max(sl[tid]&255,ban);}}int cm=cardMinute(target,pid*173+round*977+n*101,true);addMinute(target,12,cm);int played="1".equals(target[5])?cm:Math.max(1,cm-startMinute(target)+1);target[6]=String.valueOf(Math.min(Integer.parseInt(target[6]),played));counts[2+side]++;if(earliest[side]==0||cm<earliest[side])earliest[side]=cm;int applied=rate(target,-7);pfmRatingPost36.adjust(tid,applied);}}for(int i=0;i<ps.size();i++){String[] p=ps.get(i);if("M".equals(p[0])){p=grow(p,18);p[13]=String.valueOf(counts[0]);p[14]=String.valueOf(counts[1]);p[15]=String.valueOf(counts[2]);p[16]=String.valueOf(counts[3]);disciplineFlow(p,counts);redFlow(p,earliest);ps.set(i,p);}}goalkeeperFlow(ps);edit.putString(e.getKey(),serialize(ps));}edit.commit();save(pfmDiscipline70.class);}catch(Throwable ignored){}}
    public static int keeperSaves(int round,dw team){try{String wanted=teamName(team);for(Map.Entry<String,?> e:prefs().getAll().entrySet()){if(!e.getKey().startsWith(prefix(round))||!(e.getValue() instanceof String))continue;String[] h=null,m=null;for(String[] p:parse((String)e.getValue())){if("H".equals(p[0]))h=p;else if("M".equals(p[0]))m=p;}if(h==null||m==null||h.length<5||m.length<7)continue;if(wanted.equals(h[1]))return Math.max(0,Integer.parseInt(m[6])-Integer.parseInt(h[4]));if(wanted.equals(h[2]))return Math.max(0,Integer.parseInt(m[5])-Integer.parseInt(h[3]));}}catch(Throwable ignored){}return -1;}
    public static String report(int round,dw home,dw away){try{return prefs().getString(key(round,home,away),"");}catch(Throwable x){return "";}}
}
