import android.content.*;
import java.lang.reflect.*;
import java.util.*;
import pfm.android.AndroidRuntime;

/** Idempotent bridge from native ownership to the still-active legacy match roster. */
public final class PfmNativeRosterAdapter {
    private static final String PREFS="pfm_native_legacy_ids_v58";
    private PfmNativeRosterAdapter() {}
    private static Field field(Class<?> c,String n,Class<?> t)throws Exception{for(Field f:c.getDeclaredFields())if(f.getName().equals(n)&&f.getType()==t){f.setAccessible(true);return f;}throw new NoSuchFieldException(c.getName()+"."+n);}
    private static SharedPreferences prefs(){return AndroidRuntime.context().getSharedPreferences(PREFS,0);}
    private static dw user(){return pfmPlayerHistoryV2.userTeam();}
    private static int ub(Object o,String n)throws Exception{return field(o.getClass(),n,Byte.TYPE).getByte(o)&255;}
    private static boolean contains(short[] ids,int count,int id){for(int i=0;i<count&&i<ids.length;i++)if((ids[i]&65535)==id)return true;return false;}
    public static String preflight(String uid){try{dw t=user();ci[] all=(ci[])field(cp.class,"a",ci[].class).get(null);short[] ids=(short[])field(dw.class,"a",short[].class).get(t);int n=ub(t,"e");if(n>=ids.length)return "Legacy squad is full ("+n+"/"+ids.length+")";if(all.length>=32767)return "Legacy player index limit reached";return "OK";}catch(Throwable x){return "Legacy roster unavailable: "+x.getClass().getSimpleName();}}
    private static String text(ci p){try{return new String((byte[])field(ci.class,"a",byte[].class).get(p),"ISO-8859-1").trim();}catch(Throwable x){return "";}}
    private static int existing(dw t,ci[] all,String name,int age,int pos,int spe,int res,int qua)throws Exception{short[] ids=(short[])field(dw.class,"a",short[].class).get(t);int n=ub(t,"e");for(int i=0;i<n;i++){int id=ids[i]&65535;if(id>=all.length||all[id]==null)continue;ci p=all[id];if(text(p).equalsIgnoreCase(name)&&ub(p,"a")==age&&ub(p,"b")==pos&&ub(p,"c")==spe&&ub(p,"d")==res&&ub(p,"e")==qua)return id;}return -1;}
    private static int number(dw t,ci[] all)throws Exception{boolean[] used=new boolean[100];short[] ids=(short[])field(dw.class,"a",short[].class).get(t);int n=ub(t,"e");for(int i=0;i<n;i++){int id=ids[i]&65535;if(id<all.length&&all[id]!=null){int x=ub(all[id],"f");if(x<100)used[x]=true;}}for(int i=1;i<100;i++)if(!used[i])return i;return 99;}
    private static void extendSidecars(int oldSize){String[] names={"pfmCondition60","pfmDiscipline70","pfmPlayerStats","pfmGoalkeeperStats31","pfmContrib80","pfmRatingPost36"};for(String name:names)try{Class<?> c=Class.forName(name);for(Field f:c.getDeclaredFields()){if(!Modifier.isStatic(f.getModifiers())||!f.getType().isArray())continue;Class<?> component=f.getType().getComponentType();if(!component.isPrimitive())continue;f.setAccessible(true);Object old=f.get(null);if(old==null||Array.getLength(old)!=oldSize)continue;Object next=Array.newInstance(component,oldSize+1);System.arraycopy(old,0,next,0,oldSize);f.set(null,next);}}catch(Throwable ignored){}}
    private static void set(Object o,String n,Class<?> type,Object value)throws Exception{Field f=field(o.getClass(),n,type);if(type==Byte.TYPE)f.setByte(o,((Number)value).byteValue());else if(type==Integer.TYPE)f.setInt(o,((Number)value).intValue());else f.set(o,value);}
    public static synchronized String removePlayer(String uid,String name,int age,int pos,int spe,int res,int qua,int newBalance){try{dw t=user();ci[] all=(ci[])field(cp.class,"a",ci[].class).get(null);short[] ids=(short[])field(dw.class,"a",short[].class).get(t);int count=ub(t,"e"),found=existing(t,all,name,age,pos,spe,res,qua);if(found<0)return "ALREADY_REMOVED";int slot=-1;for(int i=0;i<count;i++)if((ids[i]&65535)==found){slot=i;break;}if(slot<0)return "ALREADY_REMOVED";for(int i=slot;i<count-1;i++)ids[i]=ids[i+1];ids[count-1]=0;field(dw.class,"e",Byte.TYPE).setByte(t,(byte)(count-1));field(dw.class,"g",Integer.TYPE).setInt(t,newBalance);prefs().edit().remove(uid).commit();pfmRosterIntegrity32.repairAll();pfmLineup83.snapshotAfterLoad();return "REMOVED";}catch(Throwable x){return "Legacy removal failed: "+x.getClass().getSimpleName();}}
    public static synchronized String importPlayer(String uid,String name,int age,int pos,int spe,int res,int qua,int morale,int value,int wage,int newBalance){try{dw t=user();Field playersField=field(cp.class,"a",ci[].class),countField=field(dw.class,"e",Byte.TYPE),budgetField=field(dw.class,"g",Integer.TYPE);ci[] old=(ci[])playersField.get(null);int found=existing(t,old,name,age,pos,spe,res,qua);if(found>=0){prefs().edit().putInt(uid,found).apply();return "ALREADY_SYNCED";}String ready=preflight(uid);if(!"OK".equals(ready))return ready;short[] ids=(short[])field(dw.class,"a",short[].class).get(t);int count=ub(t,"e"),oldBudget=budgetField.getInt(t);ci[] next=Arrays.copyOf(old,old.length+1);ci p=new ci();set(p,"a",byte[].class,name.getBytes("ISO-8859-1"));set(p,"a",Byte.TYPE,age);set(p,"b",Byte.TYPE,pos);set(p,"c",Byte.TYPE,spe);set(p,"d",Byte.TYPE,res);set(p,"e",Byte.TYPE,qua);set(p,"f",Byte.TYPE,number(t,old));set(p,"a",Integer.TYPE,wage);set(p,"b",Integer.TYPE,0);set(p,"c",Integer.TYPE,value);set(p,"g",Byte.TYPE,0);set(p,"h",Byte.TYPE,morale);set(p,"i",Byte.TYPE,0);set(p,"j",Byte.TYPE,ub(t,"n"));next[old.length]=p;try{playersField.set(null,next);ids[count]=(short)old.length;countField.setByte(t,(byte)(count+1));budgetField.setInt(t,newBalance);extendSidecars(old.length);pfmRosterIntegrity32.repairAll();pfmLineup83.snapshotAfterLoad();prefs().edit().putInt(uid,old.length).commit();return "SYNCED";}catch(Throwable failure){playersField.set(null,old);ids[count]=0;countField.setByte(t,(byte)count);budgetField.setInt(t,oldBudget);return "Legacy sync rolled back: "+failure.getClass().getSimpleName();}}catch(Throwable x){return "Legacy sync failed: "+x.getClass().getSimpleName();}}
}
