package pfm.android;

import android.app.*;
import android.content.*;
import java.io.*;
import java.util.*;
import org.json.*;

/** Versioned native career foundation. v1 is an audited, read-only import boundary. */
final class NativeCareerStore {
    static final int SCHEMA=12;
    static class Club {String id,name,league;int sourceId,balance,wageBudget,activeFrom=2010;}
    static class Player {String id,name,owner,nationality,provenance;int sourceId,position,age,overall,spe,res,qua,morale,value,wage,contractWage,contractUntil;boolean contractGrace;}
    static class Deal {String player,from,to;int fee,wage,years,season;boolean ai;}
    static class SaleOffer {String buyerId,buyerName,league;int fee;}
    static class Career {int schema,slot,season,created,aiWindow=-1;String activeLeague,userClub;ArrayList<Club> clubs=new ArrayList<Club>();ArrayList<Player> players=new ArrayList<Player>();ArrayList<Deal> deals=new ArrayList<Deal>();}
    private NativeCareerStore() {}
    private static File file(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".json");}
    private static File backup(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".backup.json");}
    private static String activeLeague(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("leagueCode").invoke(null));}catch(Throwable t){return NativeWorldCenter.active();}}
    private static String userClub(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("teamName").invoke(null));}catch(Throwable t){return "";}}
    private static int legacyBudget(){try{return ((Number)Class.forName("PfmTransferBridge").getMethod("budget").invoke(null)).intValue();}catch(Throwable t){return 0;}}
    private static SharedPreferences identity(Context c){return c.getSharedPreferences("pfm_native_career_identity_v67",0);}
    private static String identityKey(){return "slot_"+NativeWorldCenter.slot();}
    private static boolean sameCareer(Context c,Career old){int saved=identity(c).getInt(identityKey(),0),current=NativeWorldCenter.careerSeed();if(saved!=0&&saved!=current)return false;String league=activeLeague(),club=userClub();return league.equals(old.activeLeague)&&club.equalsIgnoreCase(old.userClub);}
    private static void markCareer(Context c,boolean fresh){String key=identityKey();SharedPreferences p=identity(c);SharedPreferences.Editor e=p.edit().putInt(key,NativeWorldCenter.careerSeed());if(fresh||!p.contains(key+"_aiAfter"))e.putInt(key+"_aiAfter",Math.max(-1,NativeWorldCenter.played()-(fresh?0:1)));e.commit();}
    static boolean aiReady(Context c){SharedPreferences p=identity(c);String key=identityKey();return p.getInt(key,0)==NativeWorldCenter.careerSeed()&&NativeWorldCenter.played()>p.getInt(key+"_aiAfter",-1);}
    private static void resetLegacy(){try{Class.forName("PfmNativeRosterAdapter").getMethod("resetCareer").invoke(null);}catch(Throwable ignored){}}
    static void postMail(Career c,Deal d){try{Player p=null;String from=d.from,to=d.to;for(Player x:c.players)if(x.id.equals(d.player))p=x;for(Club x:c.clubs){if(x.id.equals(d.from))from=x.name;if(x.id.equals(d.to))to=x.name;}if(p!=null)Class.forName("PfmNativeTransferMail").getMethod("post",String.class,String.class,String.class,String.class,Boolean.TYPE).invoke(null,p.name,from,to,NativeGlobalMarket.money(d.fee),p.overall>=85||d.fee>=15000000);}catch(Throwable ignored){}}
    private static boolean v67AiBootstrap(Career c){if(c.schema!=7||c.deals.isEmpty())return false;Club user=user(c);boolean ai=false;for(Deal d:c.deals){if(d.ai)ai=true;else if(user!=null&&(user.id.equals(d.from)||user.id.equals(d.to)))return false;}return ai;}
    private static Career imported(){Career c=new Career();c.schema=SCHEMA;c.slot=NativeWorldCenter.slot();c.season=NativeWorldCenter.season();c.created=(int)(System.currentTimeMillis()/1000L);c.activeLeague=activeLeague();c.userClub=userClub();for(String code:NativeWorldCenter.allCodes()){ArrayList<NativeWorldCenter.T> teams=NativeWorldCenter.leagues.get(code);if(teams==null)continue;for(NativeWorldCenter.T t:teams){Club club=new Club();club.id=code+":"+t.id;club.name=t.name;club.league=code;club.sourceId=t.id;club.activeFrom=t.activeFrom;c.clubs.add(club);long wages=0,values=0;for(NativeWorldCenter.P p:t.ps){Player x=new Player();x.id=p.uid;x.name=p.name;x.owner=club.id;x.nationality=p.nat.split(" • ")[0];x.provenance=p.provenance==null?"LEGACY_TOP5":p.provenance;x.sourceId=p.id;x.position=p.pos;x.age=p.age;x.overall=p.ovr;x.spe=p.spe;x.res=p.res;x.qua=p.qua;x.morale=p.mor;x.value=p.value;x.wage=p.wage;x.contractWage=p.wage;x.contractUntil=c.season+2+Math.abs(x.id.hashCode()%4);wages+=p.wage;values+=p.value;c.players.add(x);}club.wageBudget=(int)Math.min(Integer.MAX_VALUE,Math.max(1000000L,wages*115L/100L));club.balance=(int)Math.min(500000000L,Math.max(2000000L,values/4L));if(code.equals(c.activeLeague)&&t.name.equalsIgnoreCase(c.userClub))club.balance=legacyBudget();}}return c;}
    private static String validate(Career c){if(c.schema!=SCHEMA)return "unsupported schema "+c.schema;if(c.slot!=NativeWorldCenter.slot())return "wrong career slot";HashSet<String> clubs=new HashSet<String>(),players=new HashSet<String>();HashMap<String,Integer> sizes=new HashMap<String,Integer>();for(Club x:c.clubs){if(x.id==null||!clubs.add(x.id))return "duplicate club id";if(x.balance<0||x.wageBudget<=0)return "invalid club finance";sizes.put(x.id,0);}for(Player x:c.players){if(x.id==null||!players.add(x.id))return "duplicate player id";if(!clubs.contains(x.owner))return "player without owner";sizes.put(x.owner,sizes.get(x.owner)+1);if(x.age<16||x.age>50||x.position<0||x.position>3||x.spe<1||x.spe>99||x.res<1||x.res>99||x.qua<1||x.qua>99||x.morale<0||x.morale>100)return "invalid player data";if(x.contractWage<=0||x.contractUntil<c.season)return "invalid contract";}for(Club x:c.clubs){int n=sizes.get(x.id),minimum=x.league.startsWith("eu_")?13:18;if(n<minimum||n>30)return "roster outside permitted size";}if(c.clubs.size()!=227||c.players.size()<4527||c.players.size()>4865)return "unexpected import size";return "OK";}
    private static JSONObject json(Career c)throws Exception{JSONObject root=new JSONObject();root.put("schema",c.schema);root.put("slot",c.slot);root.put("season",c.season);root.put("created",c.created);root.put("aiWindow",c.aiWindow);root.put("activeLeague",c.activeLeague);root.put("userClub",c.userClub);JSONArray clubs=new JSONArray();for(Club x:c.clubs){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("league",x.league);o.put("sourceId",x.sourceId);o.put("balance",x.balance);o.put("wageBudget",x.wageBudget);o.put("activeFrom",x.activeFrom);clubs.put(o);}root.put("clubs",clubs);JSONArray players=new JSONArray();for(Player x:c.players){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("owner",x.owner);o.put("nationality",x.nationality);o.put("provenance",x.provenance);o.put("sourceId",x.sourceId);o.put("position",x.position);o.put("age",x.age);o.put("overall",x.overall);o.put("spe",x.spe);o.put("res",x.res);o.put("qua",x.qua);o.put("morale",x.morale);o.put("value",x.value);o.put("wage",x.wage);o.put("contractWage",x.contractWage);o.put("contractUntil",x.contractUntil);o.put("contractGrace",x.contractGrace);players.put(o);}root.put("players",players);JSONArray deals=new JSONArray();for(Deal x:c.deals){JSONObject o=new JSONObject();o.put("player",x.player);o.put("from",x.from);o.put("to",x.to);o.put("fee",x.fee);o.put("wage",x.wage);o.put("years",x.years);o.put("season",x.season);o.put("ai",x.ai);deals.put(o);}root.put("deals",deals);return root;}
    private static Career parse(String text)throws Exception{JSONObject root=new JSONObject(text);Career c=new Career();c.schema=root.getInt("schema");c.slot=root.getInt("slot");c.season=root.getInt("season");c.created=root.getInt("created");c.aiWindow=root.optInt("aiWindow",-1);c.activeLeague=root.optString("activeLeague");c.userClub=root.optString("userClub");JSONArray clubs=root.getJSONArray("clubs");for(int i=0;i<clubs.length();i++){JSONObject o=clubs.getJSONObject(i);Club x=new Club();x.id=o.getString("id");x.name=o.getString("name");x.league=o.getString("league");x.sourceId=o.getInt("sourceId");x.balance=o.optInt("balance",0);x.wageBudget=o.optInt("wageBudget",0);x.activeFrom=o.optInt("activeFrom",2010);c.clubs.add(x);}JSONArray players=root.getJSONArray("players");for(int i=0;i<players.length();i++){JSONObject o=players.getJSONObject(i);Player x=new Player();x.id=o.getString("id");x.name=o.getString("name");x.owner=o.getString("owner");x.nationality=o.getString("nationality");x.provenance=o.optString("provenance","LEGACY_TOP5");x.sourceId=o.getInt("sourceId");x.position=o.getInt("position");x.age=o.getInt("age");x.overall=o.getInt("overall");x.spe=o.optInt("spe",x.overall);x.res=o.optInt("res",x.overall);x.qua=o.optInt("qua",x.overall);x.morale=o.optInt("morale",55);x.value=o.getInt("value");x.wage=o.getInt("wage");x.contractWage=o.optInt("contractWage",0);x.contractUntil=o.optInt("contractUntil",0);x.contractGrace=o.optBoolean("contractGrace",false);c.players.add(x);}JSONArray deals=root.optJSONArray("deals");if(deals!=null)for(int i=0;i<deals.length();i++){JSONObject o=deals.getJSONObject(i);Deal x=new Deal();x.player=o.getString("player");x.from=o.getString("from");x.to=o.getString("to");x.fee=o.getInt("fee");x.wage=o.getInt("wage");x.years=o.getInt("years");x.season=o.getInt("season");x.ai=o.optBoolean("ai",false);c.deals.add(x);}return c;}
    private static Career migrate(Career old){
        if(old.schema==SCHEMA)return old;
        Career fresh=imported();HashMap<String,Club> fc=new HashMap<String,Club>();
        for(Club x:fresh.clubs)fc.put(x.id,x);
        HashMap<String,Player> fp=new HashMap<String,Player>();for(Player x:fresh.players)fp.put(x.id,x);
        HashSet<String> existingClubs=new HashSet<String>(),existingPlayers=new HashSet<String>();
        for(Club x:old.clubs){existingClubs.add(x.id);Club n=fc.get(x.id);if(n!=null){if(x.balance<=0)x.balance=n.balance;if(x.wageBudget<=0)x.wageBudget=n.wageBudget;}}
        for(Player x:old.players){existingPlayers.add(x.id);Player n=fp.get(x.id);if(n!=null){if(x.contractWage<=0)x.contractWage=n.contractWage;if(x.contractUntil<=0)x.contractUntil=n.contractUntil;if(old.schema<9){x.spe=n.spe;x.res=n.res;x.qua=n.qua;x.morale=n.morale;}if(old.schema<=11&&x.id.startsWith("eu:")&&x.owner.equals(n.owner)){x.position=n.position;x.age=Math.min(50,n.age+Math.max(0,old.season-fresh.season));x.overall=n.overall;x.spe=n.spe;x.res=n.res;x.qua=n.qua;x.provenance=n.provenance;}}if(x.provenance==null)x.provenance="LEGACY_TOP5";}
        if(old.schema<=9){
            for(Club x:fresh.clubs)if(x.league.startsWith("eu_")&&!existingClubs.contains(x.id))old.clubs.add(x);
            for(Player x:fresh.players)if(x.id.startsWith("eu:")&&!existingPlayers.contains(x.id))old.players.add(x);
        }
        if(old.schema==10||old.schema==11){HashMap<String,Integer> sizes=new HashMap<String,Integer>();for(Player x:old.players)sizes.put(x.owner,sizes.containsKey(x.owner)?sizes.get(x.owner)+1:1);for(Player x:fresh.players)if(x.id.startsWith("eu:")&&!existingPlayers.contains(x.id)&&sizes.containsKey(x.owner)&&sizes.get(x.owner)<30){x.age=Math.min(50,x.age+Math.max(0,old.season-fresh.season));x.contractUntil=old.season+2+Math.abs(x.id.hashCode()%4);old.players.add(x);sizes.put(x.owner,sizes.get(x.owner)+1);}}
        old.schema=SCHEMA;return old;
    }
    private static String read(File f)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));StringBuilder b=new StringBuilder();char[] q=new char[8192];int n;while((n=r.read(q))>0)b.append(q,0,n);r.close();return b.toString();}
    private static void writeAtomic(Context c,Career career)throws Exception{File target=file(c),bak=backup(c),tmp=new File(target.getParentFile(),target.getName()+".tmp");FileOutputStream out=new FileOutputStream(tmp);byte[] data=json(career).toString().getBytes("UTF-8");out.write(data);out.flush();out.getFD().sync();out.close();Career check=parse(read(tmp));String audit=validate(check);if(!"OK".equals(audit)){tmp.delete();throw new IOException(audit);}if(target.exists()){if(bak.exists())bak.delete();if(!target.renameTo(bak))throw new IOException("backup rename failed");}if(!tmp.renameTo(target)){if(bak.exists())bak.renameTo(target);throw new IOException("atomic rename failed");}}
    private static void advance(Career c,int targetSeason){Club user=null;for(Club club:c.clubs)if(club.league.equals(c.activeLeague)&&club.name.equalsIgnoreCase(c.userClub))user=club;while(c.season<targetSeason){c.season++;for(Player p:c.players){p.age=Math.min(50,p.age+1);p.morale=55;if(p.contractUntil<c.season){if(user!=null&&user.id.equals(p.owner)){p.contractUntil=c.season;p.contractGrace=true;}else{p.contractUntil=c.season+1+((p.id.hashCode()&0x7fffffff)%3);p.contractGrace=false;}}}c.aiWindow=-1;}}
    static synchronized Career ensure(Context context)throws Exception{Context c=context.getApplicationContext();File target=file(c);boolean replaced=false;if(target.exists()){try{Career old=parse(read(target));if(!sameCareer(c,old)||v67AiBootstrap(old)){resetLegacy();replaced=true;}else{boolean changed=false;if(old.schema<SCHEMA){old=migrate(old);changed=true;}int sourceSeason=NativeWorldCenter.season();if(sourceSeason>old.season){advance(old,sourceSeason);changed=true;}if("OK".equals(validate(old))){if(changed)writeAtomic(c,old);markCareer(c,false);return old;}}}catch(Throwable ignored){}}File bak=backup(c);if(!replaced&&bak.exists()){try{Career old=parse(read(bak));if(sameCareer(c,old)){old=migrate(old);int sourceSeason=NativeWorldCenter.season();if(sourceSeason>old.season)advance(old,sourceSeason);if("OK".equals(validate(old))){writeAtomic(c,old);markCareer(c,false);return old;}}}catch(Throwable ignored){}}Career fresh=imported();String audit=validate(fresh);if(!"OK".equals(audit))throw new IOException(audit);writeAtomic(c,fresh);markCareer(c,true);return fresh;}
    private static Club user(Career c){for(Club x:c.clubs)if(x.league.equals(c.activeLeague)&&x.name.equalsIgnoreCase(c.userClub))return x;return null;}
    static ArrayList<Player> userPlayers(Context context)throws Exception{Career c=ensure(context);Club club=user(c);ArrayList<Player> out=new ArrayList<Player>();if(club!=null)for(Player x:c.players)if(club.id.equals(x.owner))out.add(x);return out;}
    static ArrayList<SaleOffer> saleOffers(Context context,String playerId)throws Exception{if(!NativeTransferCalendar.open())return new ArrayList<SaleOffer>();Career c=ensure(context);Club seller=user(c);Player player=null;for(Player x:c.players)if(x.id.equals(playerId))player=x;ArrayList<SaleOffer> out=new ArrayList<SaleOffer>();if(seller==null||player==null||!seller.id.equals(player.owner))return out;final Player target=player;ArrayList<Club> candidates=new ArrayList<Club>();for(Club club:c.clubs){if(club.id.equals(seller.id)||club.league.equals(c.activeLeague))continue;int size=0;for(Player x:c.players)if(club.id.equals(x.owner))size++;int pct=85+(((player.id+":"+club.id).hashCode()&0x7fffffff)%26),fee=NativeGlobalMarket.quoted((int)Math.max(100000L,(long)player.value*pct/100L));if(size<30&&club.balance>=fee)candidates.add(club);}Collections.sort(candidates,(a,b)->Integer.compare((target.id+":"+a.id).hashCode()&0x7fffffff,(target.id+":"+b.id).hashCode()&0x7fffffff));for(int i=0;i<Math.min(3,candidates.size());i++){Club club=candidates.get(i);SaleOffer o=new SaleOffer();o.buyerId=club.id;o.buyerName=club.name;o.league=club.league;int pct=85+(((player.id+":"+club.id).hashCode()&0x7fffffff)%26);o.fee=NativeGlobalMarket.quoted((int)Math.max(100000L,(long)player.value*pct/100L));out.add(o);}return out;}
    static synchronized String sell(Context context,String playerId,String buyerId,int fee){try{if(!NativeTransferCalendar.open())return "Transfer window is closed. "+NativeTransferCalendar.status();Career c=parse(json(ensure(context)).toString());Club seller=user(c),buyer=null;Player player=null;for(Club x:c.clubs)if(x.id.equals(buyerId))buyer=x;for(Player x:c.players)if(x.id.equals(playerId))player=x;if(seller==null||buyer==null||player==null||!seller.id.equals(player.owner))return "Sale parties could not be resolved";boolean valid=false;for(SaleOffer o:saleOffers(context,playerId))if(o.buyerId.equals(buyerId)&&o.fee==fee)valid=true;if(!valid)return "This offer is no longer available";int sellerSize=0,buyerSize=0;for(Player x:c.players){if(seller.id.equals(x.owner))sellerSize++;if(buyer.id.equals(x.owner))buyerSize++;}if(sellerSize<=18)return "Your squad cannot fall below 18 players";if(buyerSize>=30)return "Buyer squad limit reached";if(buyer.balance<fee)return "Buyer can no longer afford the fee";seller.balance=(int)Math.min(Integer.MAX_VALUE,(long)seller.balance+fee);buyer.balance-=fee;player.owner=buyer.id;Deal d=new Deal();d.player=player.id;d.from=seller.id;d.to=buyer.id;d.fee=fee;d.wage=player.contractWage;d.years=Math.max(1,player.contractUntil-c.season);d.season=c.season;c.deals.add(d);String audit=validate(c);if(!"OK".equals(audit))return "Sale rolled back: "+audit;writeAtomic(context,c);applyToWorld(c);postMail(c,d);return "SOLD — "+buyer.name+" for "+NativeGlobalMarket.money(fee)+"; "+syncLegacy(c);}catch(Throwable t){return "Sale rolled back: "+String.valueOf(t.getMessage());}}
    static ArrayList<String> transferHistory(Context context,boolean all)throws Exception{Career c=ensure(context);Club user=user(c);HashMap<String,String> clubs=new HashMap<String,String>(),players=new HashMap<String,String>();for(Club x:c.clubs)clubs.put(x.id,x.name);for(Player x:c.players)players.put(x.id,x.name);ArrayList<String> out=new ArrayList<String>();for(int i=c.deals.size()-1;i>=0;i--){Deal d=c.deals.get(i);boolean mine=user!=null&&(user.id.equals(d.from)||user.id.equals(d.to));if(!all&&!mine)continue;String direction=mine?(user.id.equals(d.to)?"BOUGHT":"SOLD"):("AI TRANSFER");out.add(d.season+"  •  "+direction+"\n"+players.get(d.player)+"   "+clubs.get(d.from)+" → "+clubs.get(d.to)+"\nFee "+NativeGlobalMarket.money(d.fee)+"   wage "+NativeGlobalMarket.money(d.wage)+"/yr   "+d.years+" year"+(d.years==1?"":"s"));}return out;}
    static Career mutable(Context context)throws Exception{return parse(json(ensure(context)).toString());}
    static Club userClub(Career c){return user(c);}
    static synchronized String commitAi(Context context,Career c)throws Exception{String audit=validate(c);if(!"OK".equals(audit))return audit;writeAtomic(context,c);applyToWorld(c);return "OK";}
    static int runAiMarket(Context context){try{return NativeAiMarket.run(context);}catch(Throwable t){return -1;}}
    static synchronized String renew(Context context,String playerId,int wage,int years){try{Career c=parse(json(ensure(context)).toString());Club club=user(c);Player target=null;long payroll=0;for(Player x:c.players)if(club!=null&&club.id.equals(x.owner)){if(x.id.equals(playerId))target=x;else payroll+=x.contractWage;}if(club==null||target==null)return "Player is not in your native squad";if(years<1||years>5)return "Contract length must be 1–5 years";if(wage<target.contractWage*90L/100L)return "Player rejects a wage below 90% of his current contract";if(payroll+wage>club.wageBudget)return "Annual wage budget would be exceeded";target.contractWage=wage;target.contractUntil=c.season+years;target.contractGrace=false;String audit=validate(c);if(!"OK".equals(audit))return "Renewal rolled back: "+audit;writeAtomic(context,c);return "RENEWED — through "+target.contractUntil+" at "+NativeGlobalMarket.money(wage)+" per year";}catch(Throwable t){return "Renewal rolled back: "+String.valueOf(t.getMessage());}}
    static int balance(Context c){try{Club x=user(ensure(c));return x==null?legacyBudget():x.balance;}catch(Throwable t){return legacyBudget();}}
    static synchronized String transfer(Context context,NativeGlobalMarket.R row,int fee,int wage,int years){
        try{
            if(!NativeTransferCalendar.open())return "Transfer window is closed. "+NativeTransferCalendar.status();
            Career base=ensure(context);Career c=parse(json(base).toString());Club buyer=user(c),seller=null;Player player=null;
            for(Player x:c.players)if(x.id.equals(row.key()))player=x;
            for(Club x:c.clubs)if(player!=null&&x.id.equals(player.owner))seller=x;
            if(player==null||seller==null||buyer==null)return "Transfer parties could not be resolved";
            if(seller.activeFrom>c.season)return "Seller is not yet active in this season";
            if(seller.id.equals(buyer.id))return "Player already belongs to your club";
            int buyerSize=0,sellerSize=0;long payroll=0;
            for(Player x:c.players){if(x.owner.equals(buyer.id)){buyerSize++;payroll+=x.contractWage;}if(x.owner.equals(seller.id))sellerSize++;}
            if(buyerSize>=30)return "Squad limit reached (30)";int sellerFloor=seller.league.startsWith("eu_")?13:18;if(sellerSize<=sellerFloor)return "Seller cannot fall below "+sellerFloor+" players";
            if(fee<NativeGlobalMarket.quoted(row.ask))return "Seller has not accepted this fee";if(fee>buyer.balance)return "Insufficient transfer budget";
            if(years<1||years>5)return "Contract length must be 1–5 years";if(wage<player.wage*90L/100L)return "Player rejects a wage below 90% of his current basis";
            if(payroll+wage>buyer.wageBudget)return "Annual wage budget would be exceeded";
            buyer.balance-=fee;seller.balance=(int)Math.min(Integer.MAX_VALUE,(long)seller.balance+fee);player.owner=buyer.id;player.contractWage=wage;player.contractUntil=c.season+years;
            Deal d=new Deal();d.player=player.id;d.from=seller.id;d.to=buyer.id;d.fee=fee;d.wage=wage;d.years=years;d.season=c.season;c.deals.add(d);
            String audit=validate(c);if(!"OK".equals(audit))return "Transaction rolled back: "+audit;
            writeAtomic(context,c);applyToWorld(c);postMail(c,d);for(String code:NativeWorldCenter.C)for(NativeWorldCenter.T t:NativeWorldCenter.leagues.get(code))if(t.ps.contains(row.p)){row.code=code;row.team=t;}
            return "COMPLETED — native career ownership updated; "+syncLegacy(c);
        }catch(Throwable t){return "Transaction rolled back: "+String.valueOf(t.getMessage());}
    }
    static String syncLegacy(Career c){
        try{
            Club buyer=user(c);if(buyer==null)return "legacy matchday sync unavailable";
            HashMap<String,Player> players=new HashMap<String,Player>();for(Player x:c.players)players.put(x.id,x);
            Class<?> bridge=Class.forName("PfmNativeRosterAdapter");java.lang.reflect.Method add=bridge.getMethod("importPlayer",String.class,String.class,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE),remove=bridge.getMethod("removePlayer",String.class,String.class,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE,Integer.TYPE);
            int synced=0,known=0;String pending=null;
            for(Deal d:c.deals)if(buyer.id.equals(d.to)||buyer.id.equals(d.from)){Player x=players.get(d.player);if(x==null){pending="native player unavailable";continue;}String result=buyer.id.equals(d.to)?String.valueOf(add.invoke(null,x.id,x.name,x.age,x.position,x.spe,x.res,x.qua,x.morale,x.value,x.contractWage,buyer.balance)):String.valueOf(remove.invoke(null,x.id,x.name,x.age,x.position,x.spe,x.res,x.qua,buyer.balance));if("SYNCED".equals(result)||"REMOVED".equals(result))synced++;else if("ALREADY_SYNCED".equals(result)||"ALREADY_REMOVED".equals(result))known++;else pending=result;}
            if(pending!=null)return "legacy matchday pending: "+pending;
            return "legacy matchday OK ("+(synced+known)+" native deal"+((synced+known)==1?"":"s")+(synced>0?", "+synced+" imported":"")+")";
        }catch(Throwable t){return "legacy matchday sync unavailable: "+t.getClass().getSimpleName();}
    }
    static void applyToWorld(Career c){HashMap<String,NativeWorldCenter.P> players=new HashMap<String,NativeWorldCenter.P>();HashMap<String,NativeWorldCenter.T> clubs=new HashMap<String,NativeWorldCenter.T>();for(String code:NativeWorldCenter.allCodes()){ArrayList<NativeWorldCenter.T> ts=NativeWorldCenter.leagues.get(code);if(ts==null)continue;for(NativeWorldCenter.T t:ts){clubs.put(code+":"+t.id,t);for(NativeWorldCenter.P p:t.ps)players.put(p.uid,p);t.ps.clear();}}for(Player x:c.players){NativeWorldCenter.P p=players.get(x.id);NativeWorldCenter.T t=clubs.get(x.owner);if(p!=null&&t!=null){p.pos=x.position;p.age=x.age;p.ovr=x.overall;p.spe=x.spe;p.res=x.res;p.qua=x.qua;p.mor=x.morale;p.value=x.value;p.wage=x.wage;p.provenance=x.provenance;t.ps.add(p);}}for(NativeWorldCenter.T t:clubs.values()){int sum=0;for(NativeWorldCenter.P p:t.ps)sum+=p.ovr;t.ovr=t.ps.isEmpty()?70:sum/t.ps.size();}}
    static void show(Activity a){try{Career c=ensure(a);String audit=validate(c);File f=file(a);Club user=user(c);long payroll=0;for(Player x:c.players)if(user!=null&&x.owner.equals(user.id))payroll+=x.contractWage;int aiDeals=0,grace=0;for(Deal d:c.deals)if(d.ai)aiDeals++;for(Player p:c.players)if(user!=null&&user.id.equals(p.owner)&&p.contractGrace)grace++;String finance=user==null?"unavailable":"£"+(user.balance/1000000.0)+"m; payroll £"+(payroll/1000000.0)+"m / £"+(user.wageBudget/1000000.0)+"m";String body="Schema: "+c.schema+"\nCareer slot: "+c.slot+"\nSeason source: "+c.season+"\nActive league: "+c.activeLeague+"\nUser club: "+c.userClub+"\nClubs: "+c.clubs.size()+"\nPlayers: "+c.players.size()+"\nContracts: "+c.players.size()+" (user grace: "+grace+")\nCompleted native deals: "+c.deals.size()+" (AI: "+aiDeals+")\nAI market window: "+c.aiWindow+"\nTransfer window: "+NativeTransferCalendar.status()+"\nLegacy matchday sync: "+syncLegacy(c)+"\nClub finance: "+finance+"\nOwnership + contract audit: "+audit+"\nSnapshot: "+f.getName()+" ("+(f.length()/1024)+" KB)\nBackup policy: atomic previous-version copy\n\nNative player identity, attributes, ownership, contracts and finances are authoritative. The legacy core remains the match engine during migration.";new AlertDialog.Builder(a).setTitle("Native career data").setMessage(body).setPositiveButton("Close",null).show();}catch(Throwable t){new AlertDialog.Builder(a).setTitle("Native career data error").setMessage(String.valueOf(t.getMessage())).setPositiveButton("Close",null).show();}}
}
