package pfm.android;

import android.app.*;
import android.content.*;
import java.io.*;
import java.util.*;
import org.json.*;

/** Versioned native career foundation. v1 is an audited, read-only import boundary. */
final class NativeCareerStore {
    static final int SCHEMA=1;
    static class Club {String id,name,league;int sourceId;}
    static class Player {String id,name,owner,nationality;int sourceId,position,age,overall,value,wage;}
    static class Career {int schema,slot,season,created;String activeLeague,userClub;ArrayList<Club> clubs=new ArrayList<Club>();ArrayList<Player> players=new ArrayList<Player>();}
    private NativeCareerStore() {}
    private static File file(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".json");}
    private static File backup(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".backup.json");}
    private static String activeLeague(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("leagueCode").invoke(null));}catch(Throwable t){return NativeWorldCenter.active();}}
    private static String userClub(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("teamName").invoke(null));}catch(Throwable t){return "";}}
    private static Career imported(){Career c=new Career();c.schema=SCHEMA;c.slot=NativeWorldCenter.slot();c.season=NativeWorldCenter.season();c.created=(int)(System.currentTimeMillis()/1000L);c.activeLeague=activeLeague();c.userClub=userClub();for(String code:NativeWorldCenter.C){ArrayList<NativeWorldCenter.T> teams=NativeWorldCenter.leagues.get(code);if(teams==null)continue;for(NativeWorldCenter.T t:teams){Club club=new Club();club.id=code+":"+t.id;club.name=t.name;club.league=code;club.sourceId=t.id;c.clubs.add(club);for(NativeWorldCenter.P p:t.ps){Player x=new Player();x.id=club.id+":"+p.id;x.name=p.name;x.owner=club.id;x.nationality=p.nat.split(" • ")[0];x.sourceId=p.id;x.position=p.pos;x.age=p.age;x.overall=p.ovr;x.value=p.value;x.wage=p.wage;c.players.add(x);}}}return c;}
    private static String validate(Career c){if(c.schema!=SCHEMA)return "unsupported schema "+c.schema;if(c.slot!=NativeWorldCenter.slot())return "wrong career slot";HashSet<String> clubs=new HashSet<String>(),players=new HashSet<String>();for(Club x:c.clubs)if(x.id==null||!clubs.add(x.id))return "duplicate club id";for(Player x:c.players){if(x.id==null||!players.add(x.id))return "duplicate player id";if(!clubs.contains(x.owner))return "player without owner";if(x.age<16||x.age>50||x.position<0||x.position>3)return "invalid player data";}if(c.clubs.size()!=98||c.players.size()!=2281)return "unexpected import size";return "OK";}
    private static JSONObject json(Career c)throws Exception{JSONObject root=new JSONObject();root.put("schema",c.schema);root.put("slot",c.slot);root.put("season",c.season);root.put("created",c.created);root.put("activeLeague",c.activeLeague);root.put("userClub",c.userClub);JSONArray clubs=new JSONArray();for(Club x:c.clubs){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("league",x.league);o.put("sourceId",x.sourceId);clubs.put(o);}root.put("clubs",clubs);JSONArray players=new JSONArray();for(Player x:c.players){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("owner",x.owner);o.put("nationality",x.nationality);o.put("sourceId",x.sourceId);o.put("position",x.position);o.put("age",x.age);o.put("overall",x.overall);o.put("value",x.value);o.put("wage",x.wage);players.put(o);}root.put("players",players);return root;}
    private static Career parse(String text)throws Exception{JSONObject root=new JSONObject(text);Career c=new Career();c.schema=root.getInt("schema");c.slot=root.getInt("slot");c.season=root.getInt("season");c.created=root.getInt("created");c.activeLeague=root.optString("activeLeague");c.userClub=root.optString("userClub");JSONArray clubs=root.getJSONArray("clubs");for(int i=0;i<clubs.length();i++){JSONObject o=clubs.getJSONObject(i);Club x=new Club();x.id=o.getString("id");x.name=o.getString("name");x.league=o.getString("league");x.sourceId=o.getInt("sourceId");c.clubs.add(x);}JSONArray players=root.getJSONArray("players");for(int i=0;i<players.length();i++){JSONObject o=players.getJSONObject(i);Player x=new Player();x.id=o.getString("id");x.name=o.getString("name");x.owner=o.getString("owner");x.nationality=o.getString("nationality");x.sourceId=o.getInt("sourceId");x.position=o.getInt("position");x.age=o.getInt("age");x.overall=o.getInt("overall");x.value=o.getInt("value");x.wage=o.getInt("wage");c.players.add(x);}return c;}
    private static String read(File f)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));StringBuilder b=new StringBuilder();char[] q=new char[8192];int n;while((n=r.read(q))>0)b.append(q,0,n);r.close();return b.toString();}
    private static void writeAtomic(Context c,Career career)throws Exception{File target=file(c),bak=backup(c),tmp=new File(target.getParentFile(),target.getName()+".tmp");FileOutputStream out=new FileOutputStream(tmp);byte[] data=json(career).toString().getBytes("UTF-8");out.write(data);out.flush();out.getFD().sync();out.close();Career check=parse(read(tmp));String audit=validate(check);if(!"OK".equals(audit)){tmp.delete();throw new IOException(audit);}if(target.exists()){if(bak.exists())bak.delete();if(!target.renameTo(bak))throw new IOException("backup rename failed");}if(!tmp.renameTo(target)){if(bak.exists())bak.renameTo(target);throw new IOException("atomic rename failed");}}
    static synchronized Career ensure(Context context)throws Exception{Context c=context.getApplicationContext();File target=file(c);if(target.exists()){try{Career old=parse(read(target));if("OK".equals(validate(old)))return old;}catch(Throwable ignored){}}File bak=backup(c);if(bak.exists()){try{Career old=parse(read(bak));if("OK".equals(validate(old))){writeAtomic(c,old);return old;}}catch(Throwable ignored){}}Career fresh=imported();String audit=validate(fresh);if(!"OK".equals(audit))throw new IOException(audit);writeAtomic(c,fresh);return fresh;}
    static void show(Activity a){try{Career c=ensure(a);String audit=validate(c);File f=file(a);String body="Schema: "+c.schema+"\nCareer slot: "+c.slot+"\nSeason source: "+c.season+"\nActive league: "+c.activeLeague+"\nUser club: "+c.userClub+"\nClubs: "+c.clubs.size()+"\nPlayers: "+c.players.size()+"\nOwnership audit: "+audit+"\nSnapshot: "+f.getName()+" ("+(f.length()/1024)+" KB)\nBackup policy: atomic previous-version copy\n\nThe legacy save remains untouched. This snapshot is the migration boundary for contracts and transfers.";new AlertDialog.Builder(a).setTitle("Native career data").setMessage(body).setPositiveButton("Close",null).show();}catch(Throwable t){new AlertDialog.Builder(a).setTitle("Native career data error").setMessage(String.valueOf(t.getMessage())).setPositiveButton("Close",null).show();}}
}
