package pfm.android;

import android.app.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;

/** Cross-league offers and atomic outgoing transfers for the user's club. */
public final class NativeSales {
    private NativeSales() {}
    private static String pos(int p){return p==0?"GK":p==1?"DEF":p==2?"MID":"FW";}
    private static TextView text(Activity a,String s,float z,boolean bold){TextView v=new TextView(a);v.setText(s);v.setTextSize(z);v.setPadding(12,8,12,8);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private static void offers(Activity a,NativeCareerStore.Player player,Runnable refresh){ArrayList<NativeCareerStore.SaleOffer> offers=new ArrayList<NativeCareerStore.SaleOffer>();try{offers.addAll(NativeCareerStore.saleOffers(a,player.id));}catch(Throwable ignored){}if(offers.isEmpty()){new AlertDialog.Builder(a).setTitle(player.name).setMessage(NativeTransferCalendar.open()?"No affordable cross-league offers are available right now.":NativeTransferCalendar.status()).setPositiveButton("Close",null).show();return;}ArrayList<String> rows=new ArrayList<String>();for(NativeCareerStore.SaleOffer o:offers)rows.add(o.buyerName+"  ·  "+NativeGlobalMarket.league(o.league)+"\nOffer "+NativeGlobalMarket.money(o.fee));ListView list=new ListView(a);list.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_list_item_1,rows));AlertDialog d=new AlertDialog.Builder(a).setTitle("Offers — "+player.name).setView(list).setPositiveButton("Close",null).create();list.setOnItemClickListener((parent,v,n,id)->{NativeCareerStore.SaleOffer o=offers.get(n);new AlertDialog.Builder(a).setTitle("Accept offer?").setMessage(player.name+" will leave your club.\n\n"+o.buyerName+" — "+NativeGlobalMarket.money(o.fee)).setNegativeButton("Cancel",null).setPositiveButton("ACCEPT",(x,y)->{String result=NativeCareerStore.sell(a,player.id,o.buyerId,o.fee);d.dismiss();refresh.run();new AlertDialog.Builder(a).setTitle(result.startsWith("SOLD")?"Transfer completed":"Transfer not completed").setMessage(result).setPositiveButton("Close",null).show();}).show();});d.show();}
    public static void show(Activity a){final boolean pause=NativePause.begin();LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);TextView note=text(a,""+NativeTransferCalendar.status()+"\nSelect a player to request up to three cross-league offers. Your squad cannot fall below 18 players.",13f,false);root.addView(note);ListView list=new ListView(a);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));ArrayList<NativeCareerStore.Player> players=new ArrayList<NativeCareerStore.Player>();ArrayAdapter<NativeCareerStore.Player> adapter=new ArrayAdapter<NativeCareerStore.Player>(a,android.R.layout.simple_list_item_1,players){public View getView(int n,View old,ViewGroup parent){NativeCareerStore.Player p=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.addView(text(a,p.name+"  ·  "+pos(p.position)+"  ·  OVR "+p.overall,16f,true));row.addView(text(a,"AGE "+p.age+"   VALUE "+NativeGlobalMarket.money(p.value)+"   contract "+p.contractUntil,12.5f,false));return row;}};list.setAdapter(adapter);final Runnable[] refresh=new Runnable[1];refresh[0]=()->{players.clear();try{players.addAll(NativeCareerStore.userPlayers(a));Collections.sort(players,(x,y)->y.value-x.value);}catch(Throwable t){note.setText("Sales data unavailable: "+t.getMessage());}adapter.notifyDataSetChanged();};list.setOnItemClickListener((parent,v,n,id)->offers(a,players.get(n),refresh[0]));refresh[0].run();AlertDialog d=new AlertDialog.Builder(a).setTitle("Transfer Out Center").setView(root).setPositiveButton("Close",null).create();d.setOnDismissListener(v->NativePause.end(pause));d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();}
}
