package pfm.android;

import android.app.*;import android.graphics.Typeface;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

/** Native contract overview and atomic user-club renewals. */
public final class NativeContracts {
    private NativeContracts() {}
    private static String pos(int p){return p==0?"GK":p==1?"DEF":p==2?"MID":"FW";}
    private static TextView text(Activity a,String s,float size,boolean bold){TextView v=new TextView(a);v.setText(s);v.setTextSize(size);v.setPadding(12,8,12,8);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private static void renew(Activity a,NativeCareerStore.Player p,Runnable refresh){LinearLayout box=new LinearLayout(a);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,0,36,0);box.addView(text(a,"Current: "+NativeGlobalMarket.money(p.contractWage)+" per year, through "+p.contractUntil+"\nEnter annual wage in £ millions and a new length (1–5 years):",14f,false));EditText wage=new EditText(a);wage.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);wage.setText(String.format(Locale.US,"%.2f",p.contractWage/1000000.0));box.addView(wage);EditText years=new EditText(a);years.setInputType(InputType.TYPE_CLASS_NUMBER);years.setText("3");box.addView(years);AlertDialog d=new AlertDialog.Builder(a).setTitle("Renew — "+p.name).setView(box).setNegativeButton("Cancel",null).setPositiveButton("RENEW",null).create();d.setOnShowListener(v->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v2->{int annual,length;try{annual=(int)Math.round(Double.parseDouble(wage.getText().toString().replace(',','.'))*1000000.0);length=Integer.parseInt(years.getText().toString());}catch(Throwable t){wage.setError("Check wage and years");return;}String result=NativeCareerStore.renew(a,p.id,annual,length);boolean ok=result.startsWith("RENEWED");if(ok){d.dismiss();refresh.run();}new AlertDialog.Builder(a).setTitle(ok?"Contract renewed":"Renewal not completed").setMessage(result).setPositiveButton("Close",null).show();}));d.show();}
    public static void show(Activity a){final boolean pause=NativePause.begin();LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);TextView summary=text(a,"",13f,false);root.addView(summary);ListView list=new ListView(a);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));final ArrayList<NativeCareerStore.Player> players=new ArrayList<NativeCareerStore.Player>();final ArrayAdapter<NativeCareerStore.Player> adapter=new ArrayAdapter<NativeCareerStore.Player>(a,android.R.layout.simple_list_item_1,players){public View getView(int n,View old,ViewGroup parent){NativeCareerStore.Player p=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.addView(text(a,p.name+"  ·  "+pos(p.position)+"  ·  OVR "+p.overall,16f,true));row.addView(text(a,"AGE "+p.age+"   "+NativeGlobalMarket.money(p.contractWage)+"/yr   expires "+p.contractUntil,12.5f,false));return row;}};list.setAdapter(adapter);final Runnable[] refresh=new Runnable[1];refresh[0]=()->{players.clear();try{players.addAll(NativeCareerStore.userPlayers(a));Collections.sort(players,(x,y)->x.contractUntil!=y.contractUntil?x.contractUntil-y.contractUntil:x.name.compareToIgnoreCase(y.name));long payroll=0;for(NativeCareerStore.Player p:players)payroll+=p.contractWage;summary.setText(players.size()+" contracts  •  payroll "+NativeGlobalMarket.money((int)Math.min(Integer.MAX_VALUE,payroll))+"/yr\nTap a player to negotiate a renewal.");}catch(Throwable t){summary.setText("Contract data unavailable: "+t.getMessage());}adapter.notifyDataSetChanged();};list.setOnItemClickListener((parent,v,n,id)->renew(a,players.get(n),refresh[0]));refresh[0].run();AlertDialog d=new AlertDialog.Builder(a).setTitle("Contract Center").setView(root).setPositiveButton("Close",null).create();d.setOnDismissListener(v->NativePause.end(pause));d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();}
}
