package pfm.android;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;

/** Persistent shortlist and auditable asking-price model before cross-league transactions. */
public final class NativeGlobalMarket{
 private NativeGlobalMarket(){}
 static class R{String code;NativeWorldCenter.T team;NativeWorldCenter.P p;int ask,role,depth,sellerPct,gap,youngPct;boolean notForSale;String key(){return p.uid==null?code+":"+team.id+":"+p.id:p.uid;}}
 static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
 static TextView tx(Context c,String s,float z,boolean b){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setPadding(dp(c,8),dp(c,5),dp(c,8),dp(c,5));if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 static String pos(int p){return p==0?"GK":p==1?"DEF":p==2?"MID":"FW";}
 static String money(int n){if(n>=1000000)return String.format(Locale.US,"£%.1fm",n/1000000.0);if(n>=1000)return "£"+(n/1000)+"k";return "£"+n;}
 static int quoted(int n){return Math.max(100000,((n+50000)/100000)*100000);}
 static int budget(Context c){return NativeCareerStore.balance(c);}
 static String league(String c){for(int i=0;i<NativeWorldCenter.C.length;i++)if(c.equals(NativeWorldCenter.C[i]))return NativeWorldCenter.N[i];return c;}
 static R row(String code,NativeWorldCenter.T team,NativeWorldCenter.P p){R r=new R();r.code=code;r.team=team;r.p=p;ArrayList<NativeWorldCenter.P> same=new ArrayList<NativeWorldCenter.P>();for(NativeWorldCenter.P x:team.ps)if(x.pos==p.pos)same.add(x);Collections.sort(same,(x,y)->y.ovr-x.ovr);r.role=same.indexOf(p);r.depth=same.size();int min=p.pos==0?2:p.pos==1?5:p.pos==2?5:4,next=r.role+1<same.size()?same.get(r.role+1).ovr:p.ovr-10;r.gap=Math.max(0,p.ovr-next);int importance=r.role==0?25:r.role==1?10:0,replacement=r.depth<=min?15:r.depth==min+1?7:0,squad=team.ps.size()<=21?8:0;r.youngPct=p.age<=20?(p.ovr>=80?20:p.ovr>=70?12:8):(p.age<=22&&p.ovr>=82?12:0);r.sellerPct=Math.min(175,100+importance+replacement+squad+Math.min(15,r.gap)+r.youngPct);r.notForSale=r.role==0&&r.depth<=min&&((p.pos==0&&p.ovr>=85&&r.gap>=12)||(p.pos!=0&&p.ovr>=88&&r.gap>=12));r.ask=(int)Math.min(Integer.MAX_VALUE,Math.max(p.value,(long)Math.max(1,p.value)*r.sellerPct/100L));return r;}
 static SharedPreferences prefs(Context c){return c.getSharedPreferences("pfm_global_shortlist",0);}static boolean listed(Context c,R r){return prefs(c).getBoolean(r.key(),false);}static void toggle(Context c,R r){prefs(c).edit().putBoolean(r.key(),!listed(c,r)).apply();}
 static void profile(Activity a,R r,int cash,Runnable refresh){NativeWorldCenter.P p=r.p;String availability=r.notForSale?"not for sale — exceptional replacement risk":cash>=quoted(r.ask)?"available and affordable":"available; price exceeds your budget",neg=NativeTransferNegotiations.status(a,r);boolean accepted=neg.startsWith("PROVISIONALLY");String body="Club: "+r.team.name+" ("+league(r.code)+")\nNationality: "+p.nat.split(" • ")[0]+"\nPosition: "+pos(p.pos)+"   Age: "+p.age+"\nSPE "+p.spe+"   RES "+p.res+"   QUA "+p.qua+"   OVR "+p.ovr+"\n\nBalanced market value: "+money(p.value)+"\nEstimated asking price: "+money(quoted(r.ask))+"\nAnnual wage basis: "+money(p.wage)+"\nYour budget: "+money(cash)+"\nStatus: "+availability+(neg.length()>0?"\nNegotiation: "+neg:"")+"\n\nSeller resistance: "+r.sellerPct+"% (role, replacement gap "+r.gap+" OVR, depth "+r.depth+(r.youngPct>0?", young asset +"+r.youngPct+"%":"")+").";new AlertDialog.Builder(a).setTitle(p.name).setMessage(body).setNegativeButton(accepted?"CONTRACT":"PREPARE BID",(d,w)->{if(accepted)NativeTransferNegotiations.contract(a,r,NativeTransferNegotiations.offer(a,r),refresh);else NativeTransferNegotiations.prepare(a,r,cash,refresh);}).setNeutralButton(listed(a,r)?"REMOVE SHORTLIST":"ADD SHORTLIST",(d,w)->{toggle(a,r);refresh.run();}).setPositiveButton("Close",null).show();}
 public static void show(Activity a,ArrayList<String> codes){
  NativeCareerStore.runAiMarket(a);final int[] cash={budget(a)};ArrayList<R> all=new ArrayList<R>();for(String c:codes)for(NativeWorldCenter.T t:NativeWorldCenter.leagues.get(c))for(NativeWorldCenter.P p:t.ps)all.add(row(c,t,p));
  LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(a,8),0,dp(a,8),0);Button negotiations=new Button(a);negotiations.setText("NEGOTIATIONS");negotiations.setOnClickListener(v->NativeTransferNegotiations.show(a,all));root.addView(negotiations);Button history=new Button(a);history.setText("TRANSFER ACTIVITY");history.setOnClickListener(v->NativeTransferHistory.show(a));root.addView(history);TextView summary=tx(a,"",12f,false);root.addView(summary);EditText search=new EditText(a);search.setHint("Player, club or nationality");search.setSingleLine(true);root.addView(search);
  LinearLayout controls=new LinearLayout(a);Spinner position=new Spinner(a),sort=new Spinner(a);position.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"ALL POSITIONS","GK","DEF","MID","FW"}));sort.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"ASKING PRICE","OVERALL","AGE","NAME"}));controls.addView(position,new LinearLayout.LayoutParams(0,-2,1));controls.addView(sort,new LinearLayout.LayoutParams(0,-2,1));root.addView(controls);LinearLayout checks=new LinearLayout(a);CheckBox affordable=new CheckBox(a),available=new CheckBox(a),shortlist=new CheckBox(a);affordable.setText("Affordable");available.setText("Available");shortlist.setText("Shortlist");checks.addView(affordable,new LinearLayout.LayoutParams(0,-2,1));checks.addView(available,new LinearLayout.LayoutParams(0,-2,1));checks.addView(shortlist,new LinearLayout.LayoutParams(0,-2,1));root.addView(checks);
  ArrayList<R> shown=new ArrayList<R>();final Runnable[] refresh=new Runnable[1];ArrayAdapter<R> adapter=new ArrayAdapter<R>(a,android.R.layout.simple_list_item_1,shown){public View getView(int n,View old,ViewGroup parent){R r=getItem(n);String ns=NativeTransferNegotiations.status(a,r);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.addView(tx(a,(listed(a,r)?"★ ":"")+r.p.name+"  ·  "+r.team.name+"  ·  "+league(r.code),14f,true));row.addView(tx(a,pos(r.p.pos)+"  OVR "+r.p.ovr+"  AGE "+r.p.age+"   VALUE "+money(r.p.value)+"   ASK "+money(r.ask)+(r.notForSale?"  • not for sale":cash[0]>=r.ask?"  ✓ affordable":"")+(ns.length()>0?"\nOffer "+money(NativeTransferNegotiations.offer(a,r))+" · "+ns:""),11.5f,false));return row;}};
  ListView list=new ListView(a);list.setAdapter(adapter);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));refresh[0]=()->{cash[0]=budget(a);String q=search.getText().toString().toLowerCase(Locale.US),pf=String.valueOf(position.getSelectedItem());shown.clear();for(R r:all){String country=r.p.nat.split(" • ")[0];if(!"ALL POSITIONS".equals(pf)&&!pf.equals(pos(r.p.pos)))continue;if(affordable.isChecked()&&r.ask>cash[0])continue;if(available.isChecked()&&r.notForSale)continue;if(shortlist.isChecked()&&!listed(a,r))continue;if(q.length()>0&&!(r.p.name+" "+r.team.name+" "+country+" "+league(r.code)).toLowerCase(Locale.US).contains(q))continue;shown.add(r);}String s=String.valueOf(sort.getSelectedItem());Collections.sort(shown,(x,y)->"OVERALL".equals(s)?y.p.ovr-x.p.ovr:"AGE".equals(s)?x.p.age-y.p.age:"NAME".equals(s)?x.p.name.compareToIgnoreCase(y.p.name):Integer.compare(y.ask,x.ask));summary.setText("Shown: "+shown.size()+" / "+all.size()+"   •   Budget "+money(cash[0])+"\nTransfer window: "+NativeTransferCalendar.status()+"\nBalanced value + capped seller resistance (max 1.75×).");adapter.notifyDataSetChanged();};
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh[0].run();}public void afterTextChanged(Editable e){}});android.widget.AdapterView.OnItemSelectedListener l=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){if(refresh[0]!=null)refresh[0].run();}public void onNothingSelected(android.widget.AdapterView<?> p){}};position.setOnItemSelectedListener(l);sort.setOnItemSelectedListener(l);affordable.setOnCheckedChangeListener((b,x)->refresh[0].run());available.setOnCheckedChangeListener((b,x)->refresh[0].run());shortlist.setOnCheckedChangeListener((b,x)->refresh[0].run());list.setOnItemClickListener((p,v,n,id)->profile(a,shown.get(n),cash[0],refresh[0]));refresh[0].run();AlertDialog d=new AlertDialog.Builder(a).setTitle("Global Player Market").setView(root).setPositiveButton("Close",null).create();d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();
 }
}
