package pfm.android;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.io.*;import java.lang.reflect.*;import java.util.*;

/** Deterministic parallel top-five league viewer. Other leagues advance with the active round. */
public final class NativeWorldCenter{
 private NativeWorldCenter(){} static final String[] C={"en","es","it","de","fr"},N={"England","Spain","Italy","Germany","France"};
 static class P{int id,pos,age,ovr,spe,res,qua,mor,g,a,ap,rs,cs,ga,sv;String name,nat;} static class T{int id,ovr,p,w,d,l,gf,ga,pts;String name;ArrayList<P> ps=new ArrayList<P>();}
 static class M{int r,h,a,hg,ag;} static HashMap<String,ArrayList<T>> leagues;
 static int dp(Context c,int x){return Math.round(x*c.getResources().getDisplayMetrics().density);} static TextView tx(Context c,String s,float z,boolean b){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setPadding(dp(c,8),dp(c,6),dp(c,8),dp(c,6));if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 static void load(Context c){if(leagues!=null)return;leagues=new HashMap<String,ArrayList<T>>();for(String x:C)leagues.put(x,new ArrayList<T>());try{BufferedReader r=new BufferedReader(new InputStreamReader(c.getAssets().open("world_v42.tsv"),"UTF-8"));String s;r.readLine();while((s=r.readLine())!=null){String[] q=s.split("\t",-1);ArrayList<T> ts=leagues.get(q[1]);int ti=Integer.parseInt(q[2]);while(ts.size()<=ti)ts.add(null);if("T".equals(q[0])){T t=new T();t.id=ti;t.name=q[3];ts.set(ti,t);}else{P p=new P();p.id=Integer.parseInt(q[4]);p.name=q[5];p.pos=Integer.parseInt(q[6]);p.age=Integer.parseInt(q[7]);p.ovr=Integer.parseInt(q[8]);p.nat=q[9];p.spe=q.length>10?Integer.parseInt(q[10]):p.ovr;p.res=q.length>11?Integer.parseInt(q[11]):p.ovr;p.qua=q.length>12?Integer.parseInt(q[12]):p.ovr;p.mor=q.length>13?Integer.parseInt(q[13]):55;ts.get(ti).ps.add(p);}}r.close();for(ArrayList<T> ts:leagues.values())for(T t:ts){int sum=0,n=0;for(P p:t.ps){sum+=p.ovr;n++;}t.ovr=n==0?70:sum/n;}}catch(Throwable x){leagues.clear();}}
 static int reflect(String cl,String m){try{return ((Number)Class.forName(cl).getMethod(m).invoke(null)).intValue();}catch(Throwable x){return 0;}}
 static int played(){try{return reflect("cp","pfmPlayedForTable");}catch(Throwable x){return 0;}} static int season(){return reflect("pfm2","getSeason");} static int slot(){return reflect("pfm2","getSlot");}
 static String active(){try{Field f=Class.forName("ea").getDeclaredField("a");f.setAccessible(true);int x=f.getInt(null);return x>=0&&x<C.length?C[x]:"";}catch(Throwable t){return "";}}
 static int progress(String code){int source="de".equals(active())?34:38,target="de".equals(code)?34:38;return Math.min(target,(played()*target+source/2)/source);}
 static int hash(int x){x^=x>>>16;x*=0x7feb352d;x^=x>>>15;x*=0x846ca68b;return x^(x>>>16);}
 /** Pure-data port of bb.c(dw): the stock quick-match strength calculation for the XI. */
 static int strength(T t){int n=Math.min(11,t.ps.size()),sum=-3414;for(int i=0;i<n;i++){P p=t.ps.get(i);sum+=(p.qua*125+p.spe*85+p.res*75+p.mor*30+2600)/67;}return Math.max(1,sum);}
 /** Pure-data port of bb.a(dw,dw,...): fourteen stock quick-match attacking checks. */
 static int[] score(int seed,T home,T away){int hs=strength(home)+50,as=strength(away),ha=hs*50,hd=hs*50,aa=as*50,ad=as*50,hg=0,ag=0;for(int segment=0;segment<14;segment++){int noise=(hash(seed+segment*1009)&0x7fffffff)%20000,den=ha+ad+noise+240000;if((hash(seed+segment*1543+71)&0x7fffffff)%Math.max(1,den)<ha)hg++;noise=(hash(seed+segment*2017+991)&0x7fffffff)%20000;den=aa+hd+noise+240000;if((hash(seed+segment*2617+313)&0x7fffffff)%Math.max(1,den)<aa)ag++;}return new int[]{hg,ag};}
 static ArrayList<M> schedule(int n){ArrayList<M> out=new ArrayList<M>();int[] a=new int[n];for(int i=0;i<n;i++)a[i]=i;for(int leg=0;leg<2;leg++)for(int r=0;r<n-1;r++){for(int i=0;i<n/2;i++){M m=new M();m.r=leg*(n-1)+r+1;m.h=(leg==0?a[i]:a[n-1-i]);m.a=(leg==0?a[n-1-i]:a[i]);out.add(m);}int z=a[n-1];for(int i=n-1;i>1;i--)a[i]=a[i-1];a[1]=z;}return out;}
 static ArrayList<M> simulate(String code,int upto){return simulateAt(code,upto,season());}
 static ArrayList<M> simulateAt(String code,int upto,int seasonSeed){ArrayList<T> ts=leagues.get(code);for(T t:ts){t.p=t.w=t.d=t.l=t.gf=t.ga=t.pts=0;for(P p:t.ps)p.g=p.a=p.ap=p.rs=p.cs=p.ga=p.sv=0;}ArrayList<M> ms=schedule(ts.size());for(M m:ms)if(m.r<=upto){T h=ts.get(m.h),a=ts.get(m.a);int seed=slot()*1000003+seasonSeed*10007+code.hashCode()*101+m.r*37+m.h*11+m.a;int[] result=score(seed,h,a);m.hg=result[0];m.ag=result[1];h.p++;a.p++;h.gf+=m.hg;h.ga+=m.ag;a.gf+=m.ag;a.ga+=m.hg;if(m.hg>m.ag){h.w++;a.l++;h.pts+=3;}else if(m.hg<m.ag){a.w++;h.l++;a.pts+=3;}else{h.d++;a.d++;h.pts++;a.pts++;}stats(h,m.hg,m.ag,seed);stats(a,m.ag,m.hg,seed+17);}return ms;}
 static P pick(ArrayList<P> pool,int seed,boolean scorer){int total=0;for(P p:pool)total+=Math.max(1,p.ovr+(scorer&&p.pos==3?30:0));int x=(hash(seed)&0x7fffffff)%Math.max(1,total);for(P p:pool){x-=Math.max(1,p.ovr+(scorer&&p.pos==3?30:0));if(x<0)return p;}return pool.get(0);}
 static void stats(T t,int gf,int ga,int seed){
  ArrayList<P> order=new ArrayList<P>(t.ps);Collections.sort(order,(x,y)->y.ovr-x.ovr);
  for(P p:order){int cut=p.nat.indexOf(" • ");if(cut>=0)p.nat=p.nat.substring(0,cut);}
  int used=Math.min(14,order.size());for(int i=0;i<used;i++){P p=order.get(i);p.ap++;p.rs+=63+(gf-ga)*2+(p.ovr-t.ovr)/4+(Math.abs(hash(seed+i))%7);}
  ArrayList<P> out=new ArrayList<P>();for(int i=0;i<used;i++){P p=order.get(i);if(p.pos>=2)out.add(p);}if(out.isEmpty())out=new ArrayList<P>(order.subList(0,used));
  for(int i=0;i<gf;i++){P s=pick(out,seed+i*313,true);s.g++;if(out.size()>1&&Math.abs(hash(seed+i*719))%100<72){P x=pick(out,seed+i*977,false);if(x!=s)x.a++;}}
  for(P p:order)if(p.pos==0){p.ga+=ga;p.sv+=Math.max(0,2+Math.abs(hash(seed+41))%5-ga/2);if(ga==0)p.cs++;break;}
  for(P p:order){String extra=" • AP "+p.ap+" A "+p.a+" RAT "+(p.ap==0?"n/a":String.format(java.util.Locale.US,"%.1f",p.rs/(10.0*p.ap)));if(p.pos==0)extra+=" CS "+p.cs+" GA "+p.ga+" SV "+p.sv;p.nat+=extra;}
 }
 static ArrayAdapter<String> adapter(Activity a,ArrayList<String> rows){return new ArrayAdapter<String>(a,android.R.layout.simple_list_item_1,rows){public View getView(int p,View v,ViewGroup g){return tx(a,getItem(p),13f,p<4);}};}
 public static void show(Activity a){load(a);if(leagues.isEmpty()){Toast.makeText(a,"World data unavailable",Toast.LENGTH_SHORT).show();return;}boolean pause=NativePause.begin();LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);Spinner league=new Spinner(a);league.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,N));root.addView(league);LinearLayout buttons=new LinearLayout(a);Button table=new Button(a),results=new Button(a),players=new Button(a);table.setText("TABLE");results.setText("RESULTS");players.setText("PLAYERS");buttons.addView(table,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(results,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(players,new LinearLayout.LayoutParams(0,-2,1));root.addView(buttons);ListView list=new ListView(a);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));final int[] mode={0};Runnable refresh=()->{String code=C[league.getSelectedItemPosition()];ArrayList<T> ts=leagues.get(code);int through=progress(code);ArrayList<M> ms=simulate(code,through);ArrayList<String> rows=new ArrayList<String>();if(code.equals(active()))rows.add("This is your active competition.\nOpen LEAGUE CENTER for its exact legacy results and full match statistics.");else if(mode[0]==0){ArrayList<T> order=new ArrayList<T>(ts);Collections.sort(order,(x,y)->y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)-(x.gf-x.ga));int n=1;for(T t:order)rows.add((n++)+". "+t.name+"   "+t.pts+" pts\nP "+t.p+"  W "+t.w+" D "+t.d+" L "+t.l+"   "+t.gf+":"+t.ga);}else if(mode[0]==1){for(M m:ms)if(m.r==Math.max(1,through))rows.add(ts.get(m.h).name+"  "+m.hg+" – "+m.ag+"  "+ts.get(m.a).name);}else{ArrayList<P> ps=new ArrayList<P>();for(T t:ts)ps.addAll(t.ps);Collections.sort(ps,(x,y)->y.g!=x.g?y.g-x.g:y.ovr-x.ovr);for(P p:ps)rows.add(p.name+"   "+p.nat+"\nG "+p.g+"  OVR "+p.ovr+"  AGE "+p.age);}list.setAdapter(adapter(a,rows));};league.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){refresh.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});table.setOnClickListener(v->{mode[0]=0;refresh.run();});results.setOnClickListener(v->{mode[0]=1;refresh.run();});players.setOnClickListener(v->{mode[0]=2;refresh.run();});refresh.run();AlertDialog d=new AlertDialog.Builder(a).setTitle("World Leagues • 2010/11").setView(root).setPositiveButton("Close",null).create();d.setOnDismissListener(v->NativePause.end(pause));d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();}
}
