package pfm.android;

import android.app.*;
import android.content.*;
import java.io.*;
import java.util.*;
import org.json.*;

/** Versioned native career foundation. v1 is an audited, read-only import boundary. */
final class NativeCareerStore {
    static final int SCHEMA=3;
    static class Club {String id,name,league;int sourceId,balance,wageBudget;}
    static class Player {String id,name,owner,nationality;int sourceId,position,age,overall,value,wage,contractWage,contractUntil;}
    static class Deal {String player,from,to;int fee,wage,years,season;}
    static class Career {int schema,slot,season,created;String activeLeague,userClub;ArrayList<Club> clubs=new ArrayList<Club>();ArrayList<Player> players=new ArrayList<Player>();ArrayList<Deal> deals=new ArrayList<Deal>();}
    private NativeCareerStore() {}
    private static File file(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".json");}
    private static File backup(Context c){return new File(c.getFilesDir(),"native-career-slot-"+NativeWorldCenter.slot()+".backup.json");}
    private static String activeLeague(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("leagueCode").invoke(null));}catch(Throwable t){return NativeWorldCenter.active();}}
    private static String userClub(){try{return String.valueOf(Class.forName("PfmSeasonBridge").getMethod("teamName").invoke(null));}catch(Throwable t){return "";}}
    private static int legacyBudget(){try{return ((Number)Class.forName("PfmTransferBridge").getMethod("budget").invoke(null)).intValue();}catch(Throwable t){return 0;}}
    private static Career imported(){Career c=new Career();c.schema=SCHEMA;c.slot=NativeWorldCenter.slot();c.season=NativeWorldCenter.season();c.created=(int)(System.currentTimeMillis()/1000L);c.activeLeague=activeLeague();c.userClub=userClub();for(String code:NativeWorldCenter.C){ArrayList<NativeWorldCenter.T> teams=NativeWorldCenter.leagues.get(code);if(teams==null)continue;for(NativeWorldCenter.T t:teams){Club club=new Club();club.id=code+":"+t.id;club.name=t.name;club.league=code;club.sourceId=t.id;c.clubs.add(club);long wages=0,values=0;for(NativeWorldCenter.P p:t.ps){Player x=new Player();x.id=club.id+":"+p.id;x.name=p.name;x.owner=club.id;x.nationality=p.nat.split(" • ")[0];x.sourceId=p.id;x.position=p.pos;x.age=p.age;x.overall=p.ovr;x.value=p.value;x.wage=p.wage;x.contractWage=p.wage;x.contractUntil=c.season+2+Math.abs(x.id.hashCode()%4);wages+=p.wage;values+=p.value;c.players.add(x);}club.wageBudget=(int)Math.min(Integer.MAX_VALUE,Math.max(1000000L,wages*115L/100L));club.balance=(int)Math.min(500000000L,Math.max(2000000L,values/4L));if(code.equals(c.activeLeague)&&t.name.equalsIgnoreCase(c.userClub))club.balance=legacyBudget();}}return c;}
    private static String validate(Career c){if(c.schema!=SCHEMA)return "unsupported schema "+c.schema;if(c.slot!=NativeWorldCenter.slot())return "wrong career slot";HashSet<String> clubs=new HashSet<String>(),players=new HashSet<String>();HashMap<String,Integer> sizes=new HashMap<String,Integer>();for(Club x:c.clubs){if(x.id==null||!clubs.add(x.id))return "duplicate club id";if(x.balance<0||x.wageBudget<=0)return "invalid club finance";sizes.put(x.id,0);}for(Player x:c.players){if(x.id==null||!players.add(x.id))return "duplicate player id";if(!clubs.contains(x.owner))return "player without owner";sizes.put(x.owner,sizes.get(x.owner)+1);if(x.age<16||x.age>50||x.position<0||x.position>3)return "invalid player data";if(x.contractWage<=0||x.contractUntil<c.season)return "invalid contract";}for(int n:sizes.values())if(n<18||n>30)return "roster outside 18..30";if(c.clubs.size()!=98||c.players.size()!=2281)return "unexpected import size";return "OK";}
    private static JSONObject json(Career c)throws Exception{JSONObject root=new JSONObject();root.put("schema",c.schema);root.put("slot",c.slot);root.put("season",c.season);root.put("created",c.created);root.put("activeLeague",c.activeLeague);root.put("userClub",c.userClub);JSONArray clubs=new JSONArray();for(Club x:c.clubs){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("league",x.league);o.put("sourceId",x.sourceId);o.put("balance",x.balance);o.put("wageBudget",x.wageBudget);clubs.put(o);}root.put("clubs",clubs);JSONArray players=new JSONArray();for(Player x:c.players){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("owner",x.owner);o.put("nationality",x.nationality);o.put("sourceId",x.sourceId);o.put("position",x.position);o.put("age",x.age);o.put("overall",x.overall);o.put("value",x.value);o.put("wage",x.wage);o.put("contractWage",x.contractWage);o.put("contractUntil",x.contractUntil);players.put(o);}root.put("players",players);JSONArray deals=new JSONArray();for(Deal x:c.deals){JSONObject o=new JSONObject();o.put("player",x.player);o.put("from",x.from);o.put("to",x.to);o.put("fee",x.fee);o.put("wage",x.wage);o.put("years",x.years);o.put("season",x.season);deals.put(o);}root.put("deals",deals);return root;}
    private static Career parse(String text)throws Exception{JSONObject root=new JSONObject(text);Career c=new Career();c.schema=root.getInt("schema");c.slot=root.getInt("slot");c.season=root.getInt("season");c.created=root.getInt("created");c.activeLeague=root.optString("activeLeague");c.userClub=root.optString("userClub");JSONArray clubs=root.getJSONArray("clubs");for(int i=0;i<clubs.length();i++){JSONObject o=clubs.getJSONObject(i);Club x=new Club();x.id=o.getString("id");x.name=o.getString("name");x.league=o.getString("league");x.sourceId=o.getInt("sourceId");x.balance=o.optInt("balance",0);x.wageBudget=o.optInt("wageBudget",0);c.clubs.add(x);}JSONArray players=root.getJSONArray("players");for(int i=0;i<players.length();i++){JSONObject o=players.getJSONObject(i);Player x=new Player();x.id=o.getString("id");x.name=o.getString("name");x.owner=o.getString("owner");x.nationality=o.getString("nationality");x.sourceId=o.getInt("sourceId");x.position=o.getInt("position");x.age=o.getInt("age");x.overall=o.getInt("overall");x.value=o.getInt("value");x.wage=o.getInt("wage");x.contractWage=o.optInt("contractWage",0);x.contractUntil=o.optInt("contractUntil",0);c.players.add(x);}JSONArray deals=root.optJSONArray("deals");if(deals!=null)for(int i=0;i<deals.length();i++){JSONObject o=deals.getJSONObject(i);Deal x=new Deal();x.player=o.getString("player");x.from=o.getString("from");x.to=o.getString("to");x.fee=o.getInt("fee");x.wage=o.getInt("wage");x.years=o.getInt("years");x.season=o.getInt("season");c.deals.add(x);}return c;}
    private static Career migrate(Career old){if(old.schema==SCHEMA)return old;Career fresh=imported();HashMap<String,Club> fc=new HashMap<String,Club>();for(Club x:fresh.clubs)fc.put(x.id,x);HashMap<String,Player> fp=new HashMap<String,Player>();for(Player x:fresh.players)fp.put(x.id,x);for(Club x:old.clubs){Club n=fc.get(x.id);if(n!=null){if(x.balance<=0)x.balance=n.balance;if(x.wageBudget<=0)x.wageBudget=n.wageBudget;}}for(Player x:old.players){Player n=fp.get(x.id);if(n!=null){if(x.contractWage<=0)x.contractWage=n.contractWage;if(x.contractUntil<=0)x.contractUntil=n.contractUntil;}}old.schema=SCHEMA;return old;}
    private static String read(File f)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));StringBuilder b=new StringBuilder();char[] q=new char[8192];int n;while((n=r.read(q))>0)b.append(q,0,n);r.close();return b.toString();}
    private static void writeAtomic(Context c,Career career)throws Exception{File target=file(c),bak=backup(c),tmp=new File(target.getParentFile(),target.getName()+".tmp");FileOutputStream out=new FileOutputStream(tmp);byte[] data=json(career).toString().getBytes("UTF-8");out.write(data);out.flush();out.getFD().sync();out.close();Career check=parse(read(tmp));String audit=validate(check);if(!"OK".equals(audit)){tmp.delete();throw new IOException(audit);}if(target.exists()){if(bak.exists())bak.delete();if(!target.renameTo(bak))throw new IOException("backup rename failed");}if(!tmp.renameTo(target)){if(bak.exists())bak.renameTo(target);throw new IOException("atomic rename failed");}}
    static synchronized Career ensure(Context context)throws Exception{Context c=context.getApplicationContext();File target=file(c);if(target.exists()){try{Career old=parse(read(target));if(old.schema<SCHEMA){old=migrate(old);writeAtomic(c,old);}if("OK".equals(validate(old)))return old;}catch(Throwable ignored){}}File bak=backup(c);if(bak.exists()){try{Career old=migrate(parse(read(bak)));if("OK".equals(validate(old))){writeAtomic(c,old);return old;}}catch(Throwable ignored){}}Career fresh=imported();String audit=validate(fresh);if(!"OK".equals(audit))throw new IOException(audit);writeAtomic(c,fresh);return fresh;}
    private static Club user(Career c){for(Club x:c.clubs)if(x.league.equals(c.activeLeague)&&x.name.equalsIgnoreCase(c.userClub))return x;return null;}
    static int balance(Context c){try{Club x=user(ensure(c));return x==null?legacyBudget():x.balance;}catch(Throwable t){return legacyBudget();}}
    static synchronized String transfer(Context context,NativeGlobalMarket.R row,int fee,int wage,int years){
        try{
            Career base=ensure(context);Career c=parse(json(base).toString());Club buyer=user(c),seller=null;Player player=null;
            for(Player x:c.players)if(x.id.equals(row.key()))player=x;
            for(Club x:c.clubs)if(player!=null&&x.id.equals(player.owner))seller=x;
            if(player==null||seller==null||buyer==null)return "Transfer parties could not be resolved";
            if(seller.id.equals(buyer.id))return "Player already belongs to your club";
            int buyerSize=0,sellerSize=0;long payroll=0;
            for(Player x:c.players){if(x.owner.equals(buyer.id)){buyerSize++;payroll+=x.contractWage;}if(x.owner.equals(seller.id))sellerSize++;}
            if(buyerSize>=30)return "Squad limit reached (30)";if(sellerSize<=18)return "Seller cannot fall below 18 players";
            if(fee<NativeGlobalMarket.quoted(row.ask))return "Seller has not accepted this fee";if(fee>buyer.balance)return "Insufficient transfer budget";
            if(years<1||years>5)return "Contract length must be 1–5 years";if(wage<player.wage*90L/100L)return "Player rejects a wage below 90% of his current basis";
            if(payroll+wage>buyer.wageBudget)return "Annual wage budget would be exceeded";
            buyer.balance-=fee;seller.balance=(int)Math.min(Integer.MAX_VALUE,(long)seller.balance+fee);player.owner=buyer.id;player.contractWage=wage;player.contractUntil=c.season+years;
            Deal d=new Deal();d.player=player.id;d.from=seller.id;d.to=buyer.id;d.fee=fee;d.wage=wage;d.years=years;d.season=c.season;c.deals.add(d);
            String audit=validate(c);if(!"OK".equals(audit))return "Transaction rolled back: "+audit;
            writeAtomic(context,c);applyToWorld(c);for(String code:NativeWorldCenter.C)for(NativeWorldCenter.T t:NativeWorldCenter.leagues.get(code))if(t.ps.contains(row.p)){row.code=code;row.team=t;}
            return "COMPLETED — native career ownership updated";
        }catch(Throwable t){return "Transaction rolled back: "+String.valueOf(t.getMessage());}
    }
    static void applyToWorld(Career c){HashMap<String,NativeWorldCenter.P> players=new HashMap<String,NativeWorldCenter.P>();HashMap<String,NativeWorldCenter.T> clubs=new HashMap<String,NativeWorldCenter.T>();for(String code:NativeWorldCenter.C){ArrayList<NativeWorldCenter.T> ts=NativeWorldCenter.leagues.get(code);if(ts==null)continue;for(NativeWorldCenter.T t:ts){clubs.put(code+":"+t.id,t);for(NativeWorldCenter.P p:t.ps)players.put(p.uid,p);t.ps.clear();}}for(Player x:c.players){NativeWorldCenter.P p=players.get(x.id);NativeWorldCenter.T t=clubs.get(x.owner);if(p!=null&&t!=null)t.ps.add(p);}for(NativeWorldCenter.T t:clubs.values()){int sum=0;for(NativeWorldCenter.P p:t.ps)sum+=p.ovr;t.ovr=t.ps.isEmpty()?70:sum/t.ps.size();}}
    static void show(Activity a){try{Career c=ensure(a);String audit=validate(c);File f=file(a);Club user=user(c);long payroll=0;for(Player x:c.players)if(user!=null&&x.owner.equals(user.id))payroll+=x.contractWage;String finance=user==null?"unavailable":"£"+(user.balance/1000000.0)+"m; payroll £"+(payroll/1000000.0)+"m / £"+(user.wageBudget/1000000.0)+"m";String body="Schema: "+c.schema+"\nCareer slot: "+c.slot+"\nSeason source: "+c.season+"\nActive league: "+c.activeLeague+"\nUser club: "+c.userClub+"\nClubs: "+c.clubs.size()+"\nPlayers: "+c.players.size()+"\nContracts: "+c.players.size()+"\nCompleted native deals: "+c.deals.size()+"\nClub finance: "+finance+"\nOwnership + contract audit: "+audit+"\nSnapshot: "+f.getName()+" ("+(f.length()/1024)+" KB)\nBackup policy: atomic previous-version copy\n\nNative transfers are atomic. Matchday squads still use the legacy core until the next migration stage.";new AlertDialog.Builder(a).setTitle("Native career data").setMessage(body).setPositiveButton("Close",null).show();}catch(Throwable t){new AlertDialog.Builder(a).setTitle("Native career data error").setMessage(String.valueOf(t.getMessage())).setPositiveButton("Close",null).show();}}
}
