package pfm.android;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.io.*;import java.lang.reflect.*;import java.util.*;

/** Deterministic parallel top-five league viewer. Other leagues advance with the active round. */
public final class NativeWorldCenter{
 private NativeWorldCenter(){} static final String[] C={"en","es","it","de","fr"},N={"England","Spain","Italy","Germany","France"};
 static class P{int id,pos,age,ovr,g;String name,nat;} static class T{int id,ovr,p,w,d,l,gf,ga,pts;String name;ArrayList<P> ps=new ArrayList<P>();}
 static class M{int r,h,a,hg,ag;} static HashMap<String,ArrayList<T>> leagues;
 static int dp(Context c,int x){return Math.round(x*c.getResources().getDisplayMetrics().density);} static TextView tx(Context c,String s,float z,boolean b){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setPadding(dp(c,8),dp(c,6),dp(c,8),dp(c,6));if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 static void load(Context c){if(leagues!=null)return;leagues=new HashMap<String,ArrayList<T>>();for(String x:C)leagues.put(x,new ArrayList<T>());try{BufferedReader r=new BufferedReader(new InputStreamReader(c.getAssets().open("world_v42.tsv"),"UTF-8"));String s;r.readLine();while((s=r.readLine())!=null){String[] q=s.split("\t",-1);ArrayList<T> ts=leagues.get(q[1]);int ti=Integer.parseInt(q[2]);while(ts.size()<=ti)ts.add(null);if("T".equals(q[0])){T t=new T();t.id=ti;t.name=q[3];ts.set(ti,t);}else{P p=new P();p.id=Integer.parseInt(q[4]);p.name=q[5];p.pos=Integer.parseInt(q[6]);p.age=Integer.parseInt(q[7]);p.ovr=Integer.parseInt(q[8]);p.nat=q[9];ts.get(ti).ps.add(p);}}r.close();for(ArrayList<T> ts:leagues.values())for(T t:ts){int sum=0,n=0;for(P p:t.ps){sum+=p.ovr;n++;}t.ovr=n==0?70:sum/n;}}catch(Throwable x){leagues.clear();}}
 static int reflect(String cl,String m){try{return ((Number)Class.forName(cl).getMethod(m).invoke(null)).intValue();}catch(Throwable x){return 0;}}
 static int played(){try{return reflect("cp","pfmPlayedForTable");}catch(Throwable x){return 0;}} static int season(){return reflect("pfm2","getSeason");} static int slot(){return reflect("pfm2","getSlot");}
 static String active(){try{Field f=Class.forName("ea").getDeclaredField("a");f.setAccessible(true);int x=f.getInt(null);return x>=0&&x<C.length?C[x]:"";}catch(Throwable t){return "";}}
 static int progress(String code){int source="de".equals(active())?34:38,target="de".equals(code)?34:38;return Math.min(target,(played()*target+source/2)/source);}
 static int hash(int x){x^=x>>>16;x*=0x7feb352d;x^=x>>>15;x*=0x846ca68b;return x^(x>>>16);} static int goals(int seed,int attack,int defend,boolean home){int v=Math.abs(hash(seed)%1000),base=245+(attack-defend)*7+(home?45:0);return v<35?4:v<105?3:v<base?2:v<base+310?1:0;}
 static ArrayList<M> schedule(int n){ArrayList<M> out=new ArrayList<M>();int[] a=new int[n];for(int i=0;i<n;i++)a[i]=i;for(int leg=0;leg<2;leg++)for(int r=0;r<n-1;r++){for(int i=0;i<n/2;i++){M m=new M();m.r=leg*(n-1)+r+1;m.h=(leg==0?a[i]:a[n-1-i]);m.a=(leg==0?a[n-1-i]:a[i]);out.add(m);}int z=a[n-1];for(int i=n-1;i>1;i--)a[i]=a[i-1];a[1]=z;}return out;}
 static ArrayList<M> simulate(String code,int upto){ArrayList<T> ts=leagues.get(code);for(T t:ts){t.p=t.w=t.d=t.l=t.gf=t.ga=t.pts=0;for(P p:t.ps)p.g=0;}ArrayList<M> ms=schedule(ts.size());for(M m:ms)if(m.r<=upto){T h=ts.get(m.h),a=ts.get(m.a);int seed=slot()*1000003+season()*10007+code.hashCode()*101+m.r*37+m.h*11+m.a;m.hg=goals(seed,h.ovr,a.ovr,true);m.ag=goals(seed+991,a.ovr,h.ovr,false);h.p++;a.p++;h.gf+=m.hg;h.ga+=m.ag;a.gf+=m.ag;a.ga+=m.hg;if(m.hg>m.ag){h.w++;a.l++;h.pts+=3;}else if(m.hg<m.ag){a.w++;h.l++;a.pts+=3;}else{h.d++;a.d++;h.pts++;a.pts++;}award(h,m.hg,seed);award(a,m.ag,seed+17);}return ms;}
 static void award(T t,int n,int seed){ArrayList<P> pool=new ArrayList<P>();for(P p:t.ps)if(p.pos>=2)pool.add(p);if(pool.isEmpty())pool=t.ps;for(int i=0;i<n;i++){int total=0;for(P p:pool)total+=Math.max(1,p.ovr+(p.pos==3?30:0));int x=Math.abs(hash(seed+i*313))%total;for(P p:pool){x-=Math.max(1,p.ovr+(p.pos==3?30:0));if(x<0){p.g++;break;}}}}
 static ArrayAdapter<String> adapter(Activity a,ArrayList<String> rows){return new ArrayAdapter<String>(a,android.R.layout.simple_list_item_1,rows){public View getView(int p,View v,ViewGroup g){return tx(a,getItem(p),13f,p<4);}};}
 public static void show(Activity a){load(a);if(leagues.isEmpty()){Toast.makeText(a,"World data unavailable",Toast.LENGTH_SHORT).show();return;}boolean pause=NativePause.begin();LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);Spinner league=new Spinner(a);league.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,N));root.addView(league);LinearLayout buttons=new LinearLayout(a);Button table=new Button(a),results=new Button(a),players=new Button(a);table.setText("TABLE");results.setText("RESULTS");players.setText("PLAYERS");buttons.addView(table,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(results,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(players,new LinearLayout.LayoutParams(0,-2,1));root.addView(buttons);ListView list=new ListView(a);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));final int[] mode={0};Runnable refresh=()->{String code=C[league.getSelectedItemPosition()];ArrayList<T> ts=leagues.get(code);int through=progress(code);ArrayList<M> ms=simulate(code,through);ArrayList<String> rows=new ArrayList<String>();if(code.equals(active()))rows.add("This is your active competition.\nOpen LEAGUE CENTER for its exact legacy results and full match statistics.");else if(mode[0]==0){ArrayList<T> order=new ArrayList<T>(ts);Collections.sort(order,(x,y)->y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)-(x.gf-x.ga));int n=1;for(T t:order)rows.add((n++)+". "+t.name+"   "+t.pts+" pts\nP "+t.p+"  W "+t.w+" D "+t.d+" L "+t.l+"   "+t.gf+":"+t.ga);}else if(mode[0]==1){for(M m:ms)if(m.r==Math.max(1,through))rows.add(ts.get(m.h).name+"  "+m.hg+" – "+m.ag+"  "+ts.get(m.a).name);}else{ArrayList<P> ps=new ArrayList<P>();for(T t:ts)ps.addAll(t.ps);Collections.sort(ps,(x,y)->y.g!=x.g?y.g-x.g:y.ovr-x.ovr);for(P p:ps)rows.add(p.name+"   "+p.nat+"\nG "+p.g+"  OVR "+p.ovr+"  AGE "+p.age);}list.setAdapter(adapter(a,rows));};league.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){refresh.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});table.setOnClickListener(v->{mode[0]=0;refresh.run();});results.setOnClickListener(v->{mode[0]=1;refresh.run();});players.setOnClickListener(v->{mode[0]=2;refresh.run();});refresh.run();AlertDialog d=new AlertDialog.Builder(a).setTitle("World Leagues • 2010/11").setView(root).setPositiveButton("Close",null).create();d.setOnDismissListener(v->NativePause.end(pause));d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();}
}
