package pfm.android;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.BitmapFactory;
import android.graphics.drawable.GradientDrawable;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.lang.reflect.Method;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

/** League-wide results, every club squad and season durability diagnostics. */
public final class NativeLeagueCenter {
    private NativeLeagueCenter() {}
    private static int dp(Context c,int v){return Math.round(v*c.getResources().getDisplayMetrics().density);}
    private static TextView text(Context c,String s,float z,boolean b){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private static Class<?> bridge()throws Exception{return Class.forName("PfmLeagueBridge");}
    private static int callInt(String n){try{return ((Integer)bridge().getMethod(n).invoke(null)).intValue();}catch(Throwable t){return 0;}}
    private static String callString(String n){try{return String.valueOf(bridge().getMethod(n).invoke(null));}catch(Throwable t){return "";}}
    private static String[] rows(String n,Class<?>[] types,Object[] args){try{return (String[])bridge().getMethod(n,types).invoke(null,args);}catch(Throwable t){return new String[0];}}
    private static final class Match {String home,away;int round,homeIndex,awayIndex,hg,ag;boolean done,user;static Match parse(String s,int round){Match r=new Match();r.round=round;try{String[] p=s.split("\\t",-1);r.homeIndex=Integer.parseInt(p[1]);r.awayIndex=Integer.parseInt(p[2]);r.home=p[3];r.away=p[4];r.hg=Integer.parseInt(p[5]);r.ag=Integer.parseInt(p[6]);r.done="1".equals(p[7]);r.user="1".equals(p[8]);}catch(Throwable ignored){}return r;}}
    private static final class Team {int index,teamId=-1,count,gk,def,mid,fw,ovr,cs,ga;String name;boolean user;static Team parse(String s){Team r=new Team();try{String[] p=s.split("\\t",-1);r.index=Integer.parseInt(p[0]);r.teamId=Integer.parseInt(p[1]);r.name=p[2];r.count=Integer.parseInt(p[3]);r.gk=Integer.parseInt(p[4]);r.def=Integer.parseInt(p[5]);r.mid=Integer.parseInt(p[6]);r.fw=Integer.parseInt(p[7]);r.ovr=Integer.parseInt(p[8]);r.cs=Integer.parseInt(p[9]);r.ga=Integer.parseInt(p[10]);r.user="1".equals(p[11]);}catch(Throwable ignored){}return r;}}
    private static final class Player {String name,pos,nat="Unknown";int id,teamIndex=-1,number,age,ovr,st,ap,g,a,rat,rm,gkst,cs,ga,sv,yc,rc,fat,out;static Player parse(String s){Player r=new Player();try{String[] p=s.split("\\t",-1);r.id=Integer.parseInt(p[0]);r.number=Integer.parseInt(p[1]);r.name=p[2];r.pos=p[3];r.age=Integer.parseInt(p[4]);r.ovr=Integer.parseInt(p[5]);r.st=Integer.parseInt(p[6]);r.ap=Integer.parseInt(p[7]);r.g=Integer.parseInt(p[8]);r.a=Integer.parseInt(p[9]);r.rat=Integer.parseInt(p[10]);r.rm=Integer.parseInt(p[11]);r.gkst=Integer.parseInt(p[12]);r.cs=Integer.parseInt(p[13]);r.ga=Integer.parseInt(p[14]);r.sv=Integer.parseInt(p[15]);if(p.length>16)r.yc=Integer.parseInt(p[16]);if(p.length>17)r.rc=Integer.parseInt(p[17]);if(p.length>18)r.fat=Integer.parseInt(p[18]);if(p.length>19)r.out=Integer.parseInt(p[19]);if(p.length>20){r.nat=p[20];r.name=r.name+" · "+r.nat;}}catch(Throwable ignored){}return r;}String rating(){return rm==0?"n/a":String.format(java.util.Locale.US,"%.1f",rat/10.0);}}
    private static final class LeaguePlayer {int teamIndex;String teamName="";Player p;static LeaguePlayer parse(String raw){LeaguePlayer x=new LeaguePlayer();try{int a=raw.indexOf('\t'),b=raw.indexOf('\t',a+1);x.teamIndex=Integer.parseInt(raw.substring(0,a));x.teamName=raw.substring(a+1,b);x.p=Player.parse(raw.substring(b+1));x.p.teamIndex=x.teamIndex;}catch(Throwable ignored){x.p=new Player();}return x;}}
    private static ArrayList<Team> teams(){ArrayList<Team> out=new ArrayList<>();for(String s:rows("teamRows",new Class<?>[0],new Object[0]))out.add(Team.parse(s));return out;}
    private static ArrayList<Match> matches(int round){ArrayList<Match> out=new ArrayList<>();for(String s:rows("roundRows",new Class<?>[]{Integer.TYPE},new Object[]{Integer.valueOf(round)}))out.add(Match.parse(s,round));return out;}
    private static ArrayList<LeaguePlayer> leaguePlayers(){ArrayList<LeaguePlayer> out=new ArrayList<>();for(String s:rows("leaguePlayerRows",new Class<?>[0],new Object[0]))out.add(LeaguePlayer.parse(s));return out;}
    private static int metric(Player p,int mode){if(mode==0)return p.g;if(mode==1)return p.a;if(mode==2)return p.rm==0?-1:p.rat;if(mode==3)return p.st;if(mode==4)return p.ap;if(mode==5)return p.ovr;return p.yc+2*p.rc;}
    private static Team teamByIndex(int index){for(Team t:teams())if(t.index==index)return t;return null;}
    private static void showPlayer(Activity a,int playerId){String raw="";try{raw=String.valueOf(bridge().getMethod("playerDetail",Integer.TYPE).invoke(null,Integer.valueOf(playerId)));}catch(Throwable ignored){}if(raw.length()==0)return;String[] q=raw.split("\\t",3);if(q.length<3)return;final int ti=Integer.parseInt(q[0]);Player p=Player.parse(q[2]);String body=p.pos+"   AGE "+p.age+"   OVR "+p.ovr+"\n\nST "+p.st+"   AP "+p.ap+"   G "+p.g+"   A "+p.a+"\nRATING "+p.rating()+"   YC "+p.yc+"   RC "+p.rc+"\nFAT "+p.fat+(p.out>0?"   OUT "+p.out+"r":"   available");if("GK".equals(p.pos))body+="\n\nGK LEDGER  ST "+p.gkst+"   CS "+p.cs+"   GA "+p.ga+"   SV "+p.sv;AlertDialog d=new AlertDialog.Builder(a).setTitle("#"+p.number+" "+p.name+" — "+q[1]).setMessage(body).setNeutralButton("Open club",null).setPositiveButton("Close",null).create();d.setOnShowListener(v->{d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(x->{Team t=teamByIndex(ti);if(t!=null)showClub(a,t);});});d.show();}
    private static void showClub(Activity a,Team team){ArrayList<Player> ps=new ArrayList<>();for(String s:rows("playerRows",new Class<?>[]{Integer.TYPE},new Object[]{Integer.valueOf(team.index)})){Player p=Player.parse(s);p.teamIndex=team.index;ps.add(p);}ListView list=new ListView(a);ArrayAdapter<Player> ad=new ArrayAdapter<Player>(a,android.R.layout.simple_list_item_1,ps){@Override public View getView(int n,View cv,ViewGroup parent){LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(a,10),dp(a,5),dp(a,10),dp(a,5));Player p=getItem(n);row.addView(text(a,"#"+p.number+"  "+p.name+"  "+p.pos+"   OVR "+p.ovr,15f,true));String extra="ST "+p.st+"  AP "+p.ap+"  G "+p.g+"  A "+p.a+"  RAT "+p.rating()+"  YC "+p.yc+" RC "+p.rc+"\nFAT "+p.fat+(p.out>0?"  OUT "+p.out+"r":"  available");if("GK".equals(p.pos))extra+="\nGK LEDGER  ST "+p.gkst+"  CS "+p.cs+"  GA "+p.ga+"  SV "+p.sv;row.addView(text(a,extra,12.2f,false));return row;}};list.setAdapter(ad);list.setOnItemClickListener((parent,v,n,id)->showPlayer(a,ps.get(n).id));AlertDialog d=new AlertDialog.Builder(a).setTitle(team.name+" — "+team.count+" / 25 players").setMessage("GK "+team.gk+"  DEF "+team.def+"  MID "+team.mid+"  FW "+team.fw+"   •   OVR "+team.ovr+"\nTap a player for full details.").setView(list).setPositiveButton("Close",null).create();d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(WindowManager.LayoutParams.MATCH_PARENT,Math.round(a.getResources().getDisplayMetrics().heightPixels*.90f));});d.show();}

    private static final class MatchPlayer {int side,id=-1,number,minutes,rating;boolean starter;String name,pos,goals,assists,yellow="",red="";}
    private static final class MatchSub {int side,minute;String out,in;}
    private static final class MatchReport {String home,away;int hg,ag;int[] stats;ArrayList<String> homeGoals=new ArrayList<>(),awayGoals=new ArrayList<>();ArrayList<MatchPlayer> homePlayers=new ArrayList<>(),awayPlayers=new ArrayList<>();ArrayList<MatchSub> homeSubs=new ArrayList<>(),awaySubs=new ArrayList<>();}
    private static MatchReport report(Match m){
        String raw="";try{raw=String.valueOf(bridge().getMethod("matchReport",Integer.TYPE,Integer.TYPE,Integer.TYPE).invoke(null,Integer.valueOf(m.round),Integer.valueOf(m.homeIndex),Integer.valueOf(m.awayIndex)));}catch(Throwable ignored){}
        if(raw.length()==0)return null;MatchReport r=new MatchReport();
        try{for(String line:raw.split("\n")){String[] p=line.split("\t",-1);if(p.length==0)continue;if("H".equals(p[0])&&p.length>=5){r.home=p[1];r.away=p[2];r.hg=Integer.parseInt(p[3]);r.ag=Integer.parseInt(p[4]);}else if("G".equals(p[0])&&p.length>=5){String g=p[3]+" "+p[2]+"'"+(p[4].length()>0?" (A: "+p[4]+")":"");("0".equals(p[1])?r.homeGoals:r.awayGoals).add(g);}else if("S".equals(p[0])&&p.length>=5){MatchSub x=new MatchSub();x.side=Integer.parseInt(p[1]);x.minute=Integer.parseInt(p[2]);x.out=p[3];x.in=p[4];(x.side==0?r.homeSubs:r.awaySubs).add(x);}else if("M".equals(p[0])&&p.length>=17){r.stats=new int[16];for(int i=0;i<16;i++)r.stats[i]=Integer.parseInt(p[i+1]);}else if("P".equals(p[0])&&p.length>=10){MatchPlayer x=new MatchPlayer();x.side=Integer.parseInt(p[1]);x.number=Integer.parseInt(p[2]);x.name=p[3];x.pos=p[4];x.starter="1".equals(p[5]);x.minutes=Integer.parseInt(p[6]);x.rating=Integer.parseInt(p[7]);x.goals=p[8];x.assists=p[9];if(p.length>10)x.id=Integer.parseInt(p[10]);if(p.length>11)x.yellow=p[11];if(p.length>12)x.red=p[12];(x.side==0?r.homePlayers:r.awayPlayers).add(x);}}return r;}catch(Throwable ignored){return null;}
    }
    private static String goalBlock(ArrayList<String> goals){if(goals.isEmpty())return "—";StringBuilder b=new StringBuilder();for(String x:goals)b.append(x).append('\n');return b.toString().trim();}
    private static View matchPlayerRow(Activity a,MatchPlayer p){LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(a,3),dp(a,3),dp(a,3),dp(a,3));String rat=String.format(java.util.Locale.US,"%.1f",p.rating/10.0);row.addView(text(a,"#"+p.number+" "+p.name+"   "+rat,10.5f,p.starter));StringBuilder e=new StringBuilder(p.pos).append(" · ").append(p.minutes).append("'");if(p.goals.length()>0)e.append(" · G ").append(p.goals.replace(",","', ")).append("'");if(p.assists.length()>0)e.append(" · A ").append(p.assists.replace(",", "', ")).append("'");if(p.yellow.length()>0)e.append(" · YC ").append(p.yellow.replace(",", "', ")).append("'");if(p.red.length()>0)e.append(" · RC ").append(p.red.replace(",", "', ")).append("'");row.addView(text(a,e.toString(),9.3f,false));if(p.id>=0)row.setOnClickListener(v->showPlayer(a,p.id));return row;}
    private static TextView section(Activity a,String s){TextView v=text(a,s,9.5f,true);v.setTextColor(0xff555555);v.setPadding(dp(a,3),dp(a,6),dp(a,3),dp(a,2));return v;}
    private static View badge(Activity a,Team team,int size){if(team!=null&&team.index>=0)try{String league=String.valueOf(Class.forName("PfmSeasonBridge").getMethod("leagueCode").invoke(null));InputStream in=a.getAssets().open("badges/"+league+(team.index+1)+".png");ImageView logo=new ImageView(a);logo.setImageBitmap(BitmapFactory.decodeStream(in));logo.setScaleType(ImageView.ScaleType.FIT_CENTER);in.close();logo.setContentDescription(team.name+" badge");return logo;}catch(Throwable ignored){}TextView fallback=text(a,team==null||team.name.length()==0?"?":team.name.substring(0,1).toUpperCase(),15f,true);fallback.setTextColor(Color.WHITE);fallback.setGravity(android.view.Gravity.CENTER);GradientDrawable bg=new GradientDrawable();bg.setShape(GradientDrawable.OVAL);bg.setColor(0xff49674f);fallback.setBackground(bg);return fallback;}
    private static View teamTitle(Activity a,Team team,int color){LinearLayout r=new LinearLayout(a);r.setGravity(android.view.Gravity.CENTER);r.addView(badge(a,team,38),new LinearLayout.LayoutParams(dp(a,38),dp(a,38)));TextView n=text(a,"  "+(team==null?"?":team.name),13f,true);r.addView(n);return r;}
    private static String subsBlock(ArrayList<MatchSub> xs){if(xs.isEmpty())return "No substitutions";StringBuilder b=new StringBuilder();for(MatchSub x:xs)b.append(x.minute).append("'  ").append(x.out).append(" → ").append(x.in).append('\n');return b.toString().trim();}
    private static void statRow(Activity a,LinearLayout body,String name,int h,int aw){LinearLayout r=new LinearLayout(a);TextView l=text(a,String.valueOf(h),11f,true),n=text(a,name,10.5f,false),v=text(a,String.valueOf(aw),11f,true);l.setGravity(android.view.Gravity.END);n.setGravity(android.view.Gravity.CENTER);r.addView(l,new LinearLayout.LayoutParams(0,-2,1));r.addView(n,new LinearLayout.LayoutParams(dp(a,120),-2));r.addView(v,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);}
    /** Every result opens the facts persisted for that fixture, never today's squad totals. */
    private static void showMatch(Activity a,Match m){
        LinearLayout body=new LinearLayout(a);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(a,10),dp(a,4),dp(a,10),0);
        TextView score=text(a,m.home+"   "+(m.done?(m.hg+" – "+m.ag):"vs")+"   "+m.away,18f,true);score.setGravity(android.view.Gravity.CENTER);score.setPadding(0,dp(a,5),0,dp(a,8));body.addView(score);
        MatchReport r=report(m);if(!m.done){TextView note=text(a,"The match has not been played yet.",13f,false);note.setGravity(android.view.Gravity.CENTER);body.addView(note);}else if(r==null){TextView note=text(a,"Exact match details were not recorded for this fixture.\nThey are available for matches played after installing this build.",13f,false);note.setGravity(android.view.Gravity.CENTER);note.setPadding(0,dp(a,18),0,dp(a,18));body.addView(note);}else{
            LinearLayout goals=new LinearLayout(a);goals.setOrientation(LinearLayout.HORIZONTAL);ArrayList<String>[] gs=new ArrayList[]{r.homeGoals,r.awayGoals};int[] indexes={m.homeIndex,m.awayIndex};for(int i=0;i<2;i++){LinearLayout side=new LinearLayout(a);side.setOrientation(LinearLayout.VERTICAL);side.setPadding(dp(a,4),0,dp(a,4),dp(a,7));final int ti=indexes[i];Team titleTeam=teamByIndex(ti);View h=teamTitle(a,titleTeam,i==0?0xff315b36:0xff394b76);h.setOnClickListener(v->{Team t=teamByIndex(ti);if(t!=null)showClub(a,t);});side.addView(h);TextView g=text(a,goalBlock(gs[i]),10.3f,false);g.setGravity(android.view.Gravity.CENTER);side.addView(g);goals.addView(side,new LinearLayout.LayoutParams(0,-2,1));}body.addView(goals);
            LinearLayout subs=new LinearLayout(a);subs.setOrientation(LinearLayout.HORIZONTAL);ArrayList<MatchSub>[] ss=new ArrayList[]{r.homeSubs,r.awaySubs};for(int i=0;i<2;i++){TextView v=text(a,subsBlock(ss[i]),9.5f,false);v.setPadding(dp(a,4),dp(a,3),dp(a,4),dp(a,6));v.setGravity(android.view.Gravity.CENTER_HORIZONTAL);subs.addView(v,new LinearLayout.LayoutParams(0,-2,1));}body.addView(subs);
            TextView legend=text(a,"Tap a player or club for details   ·   rating is match-only",9.5f,false);legend.setGravity(android.view.Gravity.CENTER);legend.setPadding(0,dp(a,4),0,dp(a,4));body.addView(legend);
            LinearLayout sides=new LinearLayout(a);sides.setOrientation(LinearLayout.HORIZONTAL);ArrayList<MatchPlayer>[] ps=new ArrayList[]{r.homePlayers,r.awayPlayers};for(int i=0;i<2;i++){LinearLayout side=new LinearLayout(a);side.setOrientation(LinearLayout.VERTICAL);side.setPadding(dp(a,2),0,dp(a,2),0);side.addView(section(a,"STARTING XI"));for(MatchPlayer p:ps[i])if(p.starter)side.addView(matchPlayerRow(a,p));side.addView(section(a,"SUBSTITUTES USED"));boolean any=false;for(MatchPlayer p:ps[i])if(!p.starter){side.addView(matchPlayerRow(a,p));any=true;}if(!any)side.addView(text(a,"None",9.5f,false));sides.addView(side,new LinearLayout.LayoutParams(0,-2,1));}body.addView(sides);
            if(r.stats!=null){body.addView(section(a,"MATCH STATISTICS"));statRow(a,body,"Possession %",r.stats[0],r.stats[1]);statRow(a,body,"Shots",r.stats[2],r.stats[3]);statRow(a,body,"On target",r.stats[4],r.stats[5]);statRow(a,body,"Corners",r.stats[6],r.stats[7]);statRow(a,body,"Fouls",r.stats[8],r.stats[9]);statRow(a,body,"Offsides",r.stats[10],r.stats[11]);statRow(a,body,"Yellow cards",r.stats[12],r.stats[13]);statRow(a,body,"Red cards",r.stats[14],r.stats[15]);}
        }
        ScrollView scroll=new ScrollView(a);scroll.addView(body);AlertDialog d=new AlertDialog.Builder(a).setTitle("Matchday "+m.round+" — Match report").setView(scroll).setPositiveButton("Close",null).create();d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(WindowManager.LayoutParams.MATCH_PARENT,Math.round(a.getResources().getDisplayMetrics().heightPixels*.92f));});d.show();
    }

    public static void show(Activity a){
        try{if(!Boolean.TRUE.equals(bridge().getMethod("available").invoke(null))){Toast.makeText(a,"League data is unavailable",Toast.LENGTH_SHORT).show();return;}}catch(Throwable t){return;}
        final boolean pause=NativePause.begin();final int total=callInt("totalRounds"),played=callInt("playedMatches");final ArrayList<Team> clubs=teams();
        LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(a,8),dp(a,3),dp(a,8),0);
        LinearLayout tabs=new LinearLayout(a);tabs.setOrientation(LinearLayout.HORIZONTAL);Button results=new Button(a);results.setText("RESULTS");Button squads=new Button(a);squads.setText("CLUBS");Button playerTab=new Button(a);playerTab.setText("PLAYERS");Button durability=new Button(a);durability.setText("AUDIT");tabs.addView(results,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(squads,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(playerTab,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(durability,new LinearLayout.LayoutParams(0,-2,1));root.addView(tabs);
        Spinner round=new Spinner(a);String[] labels=new String[total];for(int i=0;i<total;i++)labels[i]="MATCHDAY "+(i+1)+(i<played?" — played":"");ArrayAdapter<String> ra=new ArrayAdapter<>(a,android.R.layout.simple_spinner_item,labels);ra.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);round.setAdapter(ra);if(total>0)round.setSelection(Math.max(0,Math.min(total-1,played==0?0:played-1)));root.addView(round);
        LinearLayout playerTools=new LinearLayout(a);playerTools.setOrientation(LinearLayout.VERTICAL);LinearLayout searchRow=new LinearLayout(a);EditText search=new EditText(a);search.setSingleLine(true);search.setHint("Player or club name");Button apply=new Button(a);apply.setText("SEARCH");searchRow.addView(search,new LinearLayout.LayoutParams(0,-2,1));searchRow.addView(apply);playerTools.addView(searchRow);LinearLayout filters=new LinearLayout(a);Spinner position=new Spinner(a),sort=new Spinner(a);String[] positions={"ALL POS","GK","DEF","MID","FW"},metrics={"GOALS","ASSISTS","RATING","STARTS","APPEARANCES","OVERALL","CARDS"};position.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,positions));sort.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,metrics));filters.addView(position,new LinearLayout.LayoutParams(0,-2,1));filters.addView(sort,new LinearLayout.LayoutParams(0,-2,1));playerTools.addView(filters);root.addView(playerTools);playerTools.setVisibility(View.GONE);
        ListView list=new ListView(a);list.setDividerHeight(1);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));
        final ArrayList<LeaguePlayer> allPlayers=leaguePlayers();final int[] mode={0};Runnable refresh=()->{
            if(mode[0]==0){final ArrayList<Match> ms=matches(round.getSelectedItemPosition()+1);list.setAdapter(new ArrayAdapter<Match>(a,android.R.layout.simple_list_item_1,ms){@Override public View getView(int n,View cv,ViewGroup p){Match m=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(android.view.Gravity.CENTER_VERTICAL);row.setPadding(dp(a,6),dp(a,8),dp(a,6),dp(a,8));TextView h=text(a,m.home,14f,m.user),sc=text(a,m.done?(m.hg+"  –  "+m.ag):"vs",15f,true),aw=text(a,m.away,14f,m.user);h.setGravity(android.view.Gravity.END);aw.setGravity(android.view.Gravity.START);sc.setGravity(android.view.Gravity.CENTER);row.addView(h,new LinearLayout.LayoutParams(0,-2,1));row.addView(sc,new LinearLayout.LayoutParams(dp(a,70),-2));row.addView(aw,new LinearLayout.LayoutParams(0,-2,1));if(m.user)row.setBackgroundColor(0xffe6f4e6);return row;}});list.setOnItemClickListener((p,v,n,id)->showMatch(a,ms.get(n)));}
            else if(mode[0]==1){list.setAdapter(new ArrayAdapter<Team>(a,android.R.layout.simple_list_item_1,clubs){@Override public View getView(int n,View cv,ViewGroup p){Team t=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(a,9),dp(a,6),dp(a,9),dp(a,6));row.addView(text(a,t.name+"   "+t.count+" / 25   OVR "+t.ovr,15f,true));row.addView(text(a,"GK "+t.gk+"  DEF "+t.def+"  MID "+t.mid+"  FW "+t.fw+"   •   CS "+t.cs+"  GA "+t.ga,12.5f,false));if(t.user)row.setBackgroundColor(0xffe6f4e6);return row;}});list.setOnItemClickListener((p,v,n,id)->showClub(a,clubs.get(n)));}
            else if(mode[0]==2){final ArrayList<LeaguePlayer> shown=new ArrayList<>();String q=search.getText().toString().trim().toLowerCase(java.util.Locale.US);String po=String.valueOf(position.getSelectedItem());final int sm=sort.getSelectedItemPosition();for(LeaguePlayer x:allPlayers)if(x.p!=null&&(po.startsWith("ALL")||po.equals(x.p.pos))&&(q.length()==0||x.p.name.toLowerCase(java.util.Locale.US).contains(q)||x.teamName.toLowerCase(java.util.Locale.US).contains(q)))shown.add(x);Collections.sort(shown,new Comparator<LeaguePlayer>(){public int compare(LeaguePlayer x,LeaguePlayer y){int d=metric(y.p,sm)-metric(x.p,sm);return d!=0?d:x.p.name.compareToIgnoreCase(y.p.name);}});list.setAdapter(new ArrayAdapter<LeaguePlayer>(a,android.R.layout.simple_list_item_1,shown){@Override public View getView(int n,View cv,ViewGroup p){LeaguePlayer x=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(a,8),dp(a,5),dp(a,8),dp(a,5));row.addView(text(a,(n+1)+".  "+x.p.name+"   "+x.p.pos+"   "+x.teamName,14f,true));row.addView(text(a,"G "+x.p.g+"  A "+x.p.a+"  RAT "+x.p.rating()+"  ST "+x.p.st+"  AP "+x.p.ap+"  OVR "+x.p.ovr+"  YC "+x.p.yc+" RC "+x.p.rc,11.5f,false));return row;}});list.setOnItemClickListener((p,v,n,id)->showPlayer(a,shown.get(n).p.id));}
            else{String[] x=callString("durability").split("\\t",-1);String body="Finish a 38-round season to compare the simulation with the real 2010/11 league benchmark.";try{int p=Integer.parseInt(x[0]),all38=Integer.parseInt(x[2]),all37=Integer.parseInt(x[3]),target=Integer.parseInt(x[12]);body="Season progress: "+p+" / "+x[1]+"\n\n38 starts: "+all38+"\n37 starts: "+all37+"\nTOTAL: "+(all38+all37)+"   •   real 2010/11 target: "+target+"\n\nBy position (38 + 37)\nGK  "+x[4]+" + "+x[5]+"\nDEF "+x[6]+" + "+x[7]+"\nMID "+x[8]+" + "+x[9]+"\nFW  "+x[10]+" + "+x[11]+"\n\n"+callString("rosterAudit");}catch(Throwable ignored){}ArrayList<String> one=new ArrayList<>();one.add(body);list.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_list_item_1,one){@Override public View getView(int n,View cv,ViewGroup p){TextView v=text(a,getItem(n),14f,false);v.setPadding(dp(a,12),dp(a,12),dp(a,12),dp(a,12));return v;}});list.setOnItemClickListener(null);}
            round.setVisibility(mode[0]==0?View.VISIBLE:View.GONE);playerTools.setVisibility(mode[0]==2?View.VISIBLE:View.GONE);};
        round.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){refresh.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});android.widget.AdapterView.OnItemSelectedListener filterListener=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){if(mode[0]==2)refresh.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}};position.setOnItemSelectedListener(filterListener);sort.setOnItemSelectedListener(filterListener);results.setOnClickListener(v->{mode[0]=0;refresh.run();});squads.setOnClickListener(v->{mode[0]=1;refresh.run();});playerTab.setOnClickListener(v->{mode[0]=2;refresh.run();});durability.setOnClickListener(v->{mode[0]=3;refresh.run();});apply.setOnClickListener(v->refresh.run());refresh.run();
        TextView note=text(a,"GK ledger: "+callInt("goalkeeperTrackedMatches")+" matchdays recorded (current R"+callInt("goalkeeperTrackedThrough")+"). CS/GA are exact; SV is the added deterministic keeper-stat simulation.",11f,false);note.setPadding(dp(a,5),dp(a,3),dp(a,5),dp(a,3));root.addView(note);
        AlertDialog d=new AlertDialog.Builder(a).setTitle("League Center").setView(root).setPositiveButton("Close",null).create();d.setOnDismissListener(v->NativePause.end(pause));d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(WindowManager.LayoutParams.MATCH_PARENT,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();
    }
}
