package pfm.android;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;

/** Persistent shortlist and auditable asking-price model before cross-league transactions. */
public final class NativeGlobalMarket{
 private NativeGlobalMarket(){}
 static class R{String code;NativeWorldCenter.T team;NativeWorldCenter.P p;int ask,role,depth;boolean protectedPlayer;String key(){return code+":"+team.id+":"+p.id;}}
 static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
 static TextView tx(Context c,String s,float z,boolean b){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setPadding(dp(c,8),dp(c,5),dp(c,8),dp(c,5));if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 static String pos(int p){return p==0?"GK":p==1?"DEF":p==2?"MID":"FW";}
 static String money(int n){if(n>=1000000)return String.format(Locale.US,"£%.1fm",n/1000000.0);if(n>=1000)return "£"+(n/1000)+"k";return "£"+n;}
 static int budget(){try{return ((Number)Class.forName("PfmTransferBridge").getMethod("budget").invoke(null)).intValue();}catch(Throwable t){return 0;}}
 static String league(String c){for(int i=0;i<NativeWorldCenter.C.length;i++)if(c.equals(NativeWorldCenter.C[i]))return NativeWorldCenter.N[i];return c;}
 static int ageFactor(int age){return age<=21?145:age<=24?130:age<=28?110:age<=31?90:75;}
 static R row(String code,NativeWorldCenter.T team,NativeWorldCenter.P p){R r=new R();r.code=code;r.team=team;r.p=p;ArrayList<NativeWorldCenter.P> same=new ArrayList<NativeWorldCenter.P>();for(NativeWorldCenter.P x:team.ps)if(x.pos==p.pos)same.add(x);Collections.sort(same,(x,y)->y.ovr-x.ovr);r.role=same.indexOf(p);r.depth=same.size();int roleFactor=r.role==0?150:r.role==1?125:100,min=p.pos==0?2:p.pos==1?5:p.pos==2?5:4,depthFactor=r.depth<=min?140:r.depth==min+1?115:100,squadFactor=team.ps.size()<=21?120:100;long ask=(long)Math.max(1,p.value)*ageFactor(p.age)*roleFactor*depthFactor*squadFactor/100000000L;r.ask=(int)Math.min(Integer.MAX_VALUE,Math.max(p.value,ask));r.protectedPlayer=(r.role<2&&r.depth<=min)||team.ps.size()<=20;return r;}
 static SharedPreferences prefs(Context c){return c.getSharedPreferences("pfm_global_shortlist",0);}static boolean listed(Context c,R r){return prefs(c).getBoolean(r.key(),false);}static void toggle(Context c,R r){prefs(c).edit().putBoolean(r.key(),!listed(c,r)).apply();}
 static void profile(Activity a,R r,int cash,Runnable refresh){NativeWorldCenter.P p=r.p;String availability=r.protectedPlayer?"club considers him essential":cash>=r.ask?"asking price is affordable":"asking price exceeds your budget";String body="Club: "+r.team.name+" ("+league(r.code)+")\nNationality: "+p.nat.split(" • ")[0]+"\nPosition: "+pos(p.pos)+"   Age: "+p.age+"\nSPE "+p.spe+"   RES "+p.res+"   QUA "+p.qua+"   OVR "+p.ovr+"\n\nDatabase value: "+money(p.value)+"\nEstimated asking price: "+money(r.ask)+"\nAnnual wage basis: "+money(p.wage)+"\nYour budget: "+money(cash)+"\nStatus: "+availability+"\n\nPrice factors: age "+ageFactor(p.age)+"%, role "+(r.role==0?150:r.role==1?125:100)+"%, positional depth "+r.depth+".";new AlertDialog.Builder(a).setTitle(p.name).setMessage(body).setNeutralButton(listed(a,r)?"REMOVE SHORTLIST":"ADD SHORTLIST",(d,w)->{toggle(a,r);refresh.run();}).setPositiveButton("Close",null).show();}
 public static void show(Activity a,ArrayList<String> codes){
  int cash=budget();ArrayList<R> all=new ArrayList<R>();for(String c:codes)for(NativeWorldCenter.T t:NativeWorldCenter.leagues.get(c))for(NativeWorldCenter.P p:t.ps)all.add(row(c,t,p));
  LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(a,8),0,dp(a,8),0);TextView summary=tx(a,"",12f,false);root.addView(summary);EditText search=new EditText(a);search.setHint("Player, club or nationality");search.setSingleLine(true);root.addView(search);
  LinearLayout controls=new LinearLayout(a);Spinner position=new Spinner(a),sort=new Spinner(a);position.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"ALL POSITIONS","GK","DEF","MID","FW"}));sort.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"ASKING PRICE","OVERALL","AGE","NAME"}));controls.addView(position,new LinearLayout.LayoutParams(0,-2,1));controls.addView(sort,new LinearLayout.LayoutParams(0,-2,1));root.addView(controls);LinearLayout checks=new LinearLayout(a);CheckBox affordable=new CheckBox(a),shortlist=new CheckBox(a);affordable.setText("Affordable");shortlist.setText("Shortlist");checks.addView(affordable,new LinearLayout.LayoutParams(0,-2,1));checks.addView(shortlist,new LinearLayout.LayoutParams(0,-2,1));root.addView(checks);
  ArrayList<R> shown=new ArrayList<R>();final Runnable[] refresh=new Runnable[1];ArrayAdapter<R> adapter=new ArrayAdapter<R>(a,android.R.layout.simple_list_item_1,shown){public View getView(int n,View old,ViewGroup parent){R r=getItem(n);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.VERTICAL);row.addView(tx(a,(listed(a,r)?"★ ":"")+r.p.name+"  ·  "+r.team.name+"  ·  "+league(r.code),14f,true));row.addView(tx(a,pos(r.p.pos)+"  OVR "+r.p.ovr+"  AGE "+r.p.age+"   ASK "+money(r.ask)+(r.protectedPlayer?"  • essential":cash>=r.ask?"  ✓ affordable":""),11.5f,false));return row;}};
  ListView list=new ListView(a);list.setAdapter(adapter);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));refresh[0]=()->{String q=search.getText().toString().toLowerCase(Locale.US),pf=String.valueOf(position.getSelectedItem());shown.clear();for(R r:all){String country=r.p.nat.split(" • ")[0];if(!"ALL POSITIONS".equals(pf)&&!pf.equals(pos(r.p.pos)))continue;if(affordable.isChecked()&&(r.ask>cash||r.protectedPlayer))continue;if(shortlist.isChecked()&&!listed(a,r))continue;if(q.length()>0&&!(r.p.name+" "+r.team.name+" "+country+" "+league(r.code)).toLowerCase(Locale.US).contains(q))continue;shown.add(r);}String s=String.valueOf(sort.getSelectedItem());Collections.sort(shown,(x,y)->"OVERALL".equals(s)?y.p.ovr-x.p.ovr:"AGE".equals(s)?x.p.age-y.p.age:"NAME".equals(s)?x.p.name.compareToIgnoreCase(y.p.name):Integer.compare(y.ask,x.ask));summary.setText("Shown: "+shown.size()+" / "+all.size()+"   •   Budget "+money(cash)+"\nAsking prices include age, role, squad size and positional depth.");adapter.notifyDataSetChanged();};
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh[0].run();}public void afterTextChanged(Editable e){}});android.widget.AdapterView.OnItemSelectedListener l=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int n,long id){if(refresh[0]!=null)refresh[0].run();}public void onNothingSelected(android.widget.AdapterView<?> p){}};position.setOnItemSelectedListener(l);sort.setOnItemSelectedListener(l);affordable.setOnCheckedChangeListener((b,x)->refresh[0].run());shortlist.setOnCheckedChangeListener((b,x)->refresh[0].run());list.setOnItemClickListener((p,v,n,id)->profile(a,shown.get(n),cash,refresh[0]));refresh[0].run();AlertDialog d=new AlertDialog.Builder(a).setTitle("Global Player Market").setView(root).setPositiveButton("Close",null).create();d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null)w.setLayout(-1,Math.round(a.getResources().getDisplayMetrics().heightPixels*.94f));});d.show();
 }
}
