#!/usr/bin/env python3
"""Reconcile v74 with independently sourced 2010/11 positions/appearances.

The opening-day game snapshot is a curated approximation: season-end tables
include winter moves, so a player is added only when not already owned and
when his identity is unambiguous. Sources remain in roster_facts.tsv.
"""
import argparse
import csv
import difflib
import hashlib
import re
import unicodedata
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path


def key(s):
    return re.sub(r"[^a-z0-9]", "", unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower())


def stable(s, n):
    return int(hashlib.sha256(s.encode()).hexdigest()[:12], 16) % n


def same_person(a, b):
    aa=[key(t) for t in a.split()];bb=[key(t) for t in b.split()]
    if not aa or not bb:return False
    if key(a)==key(b):return True
    if len(aa)==1 or len(bb)==1:
        return min(len(key(a)),len(key(b)))>=6 and (key(a) in key(b) or key(b) in key(a))
    first=difflib.SequenceMatcher(None,aa[0],bb[0]).ratio()
    last=difflib.SequenceMatcher(None,aa[-1],bb[-1]).ratio()
    return first>=.73 and last>=.78 and difflib.SequenceMatcher(None,key(a),key(b)).ratio()>=.78


FIRST_ALIASES={'aljaksandr':'aleksandr','alyaksey':'aleksey','andrey':'andrey','andrij':'andriy',
 'dzmitryj':'dmitriy','georgios':'giourkas','ihar':'igor','ihor':'igor','jaroslav':'yaroslav',
 'jevgenij':'yevhen','konstantinos':'kostas','pat':'patrick','sergej':'sergey','sjarhej':'sergey',
 'syarhey':'sergey','vitalij':'vitaliy','vasilij':'vasiliy','billy':'william'}
# Reviewed transliterations which the general matcher must not guess from
# whole-name similarity. The club scope prevents a same-name cross-club join.
EXPLICIT_ALIASES={
 ('eu_belarus_dinamo-minsk','olegstrakhanovich'):'alehstrakhanovich',
 ('eu_cyprus_apoel','mariosilia'):'marioselia',
 ('eu_israel_maccabi-tel-aviv','tamirkahlon'):'tamircahalon',
 ('eu_netherlands_feyenoord','fedorsmolov'):'fjodorsmolov',
 ('eu_turkey_bursaspor','sercanyldrm'):'sercanyildirim',
 ('eu_ukraine_dynamo-kyiv','artemkravets'):'artemkravec',
 ('eu_denmark_fc-nordsjlland','andreasgranskov'):'andreasgranskovhansen',
 ('eu_greece_aek-athens','nachoscocco'):'ignacioscocco',
 ('eu_greece_panathinaikos','luisgarcia'):'luisgarciasanz',
 ('eu_norway_molde-fk','bayedjibyfall'):'djibyfall',
 ('eu_portugal_rio-ave','josegomes'):'zegomes',
 ('eu_portugal_sl-benfica','maxipereira'):'maximilianopereira',
 ('eu_russia_anzhi-makhachkala','bayealiibrakebe'):'ibrakebe',
 ('eu_russia_anzhi-makhachkala','davidtsoraev'):'davidcorajev',
 ('eu_russia_cska-moscow','alexeyberezutskiy'):'aleksejberezuckij',
 ('eu_russia_dynamo-moscow','dmitriykhokhlov'):'dmitrijchochlov',
 ('eu_scotland_celtic','kisungyueng'):'sungyuengki',
 ('eu_scotland_celtic','chaduri'):'duricha',
 ('eu_scotland_rangers','richardfoster'):'rickyfoster',
 ('eu_sweden_ifk-goteborg','theodorelmarbjarnason'):'elmarbjarnason',
 ('eu_switzerland_fc-basel','gillesyapi'):'gillesyapiyapo',
 ('eu_turkey_besiktas','mertnobre'):'marcionobre',
 ('eu_turkey_bursaspor','gokcekvederson'):'wederson',
 ('eu_ukraine_shakhtar-donetsk','dmytrochygrynskiy'):'dmytrocyhrynskyj',
 ('eu_ukraine_shakhtar-donetsk','yaroslavrakitskiy'):'jaroslavrakickyj',
 ('eu_ukraine_shakhtar-donetsk','vitaliyvitsenets'):'vitalijvicenec',
 ('eu_ukraine_vorskla-poltava','serhiydolhanskyi'):'sergejdolganskij',
}
# Confirmed duplicate generated by the old short-list import. The Cyprus FA
# lists one Marios Ilia/Elia, defender, for APOEL in 2010/11.
DUPLICATE_UIDS={'eu:marioselia'}
DATE_CONFLICT_UIDS={'eu:oleksandrrybka','eu:ilsinho','eu:mariuszlewandowski'}
def person_parts(s):
    q=[key(x) for x in s.replace('-',' ').split() if key(x)]
    if not q:return ('','')
    first=FIRST_ALIASES.get(q[0],q[0]);last=q[-1]
    for a,b in [('w','v'),('cz','ch'),('sz','sh'),('j','y'),('ij','iy')]:last=last.replace(a,b)
    return first,last

def identity_match(a,b):
    if same_person(a,b):return True
    af,al=person_parts(a);bf,bl=person_parts(b)
    return (difflib.SequenceMatcher(None,af,bf).ratio()>=.82 and
            difflib.SequenceMatcher(None,al,bl).ratio()>=.78)


def read(p):
    with p.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def age(dob, calendar=False):
    d, m, y = map(int, dob.split("."))
    start = date(2010, 3 if calendar else 8, 1)
    return start.year-y-((start.month,start.day)<(m,d))


STRONG={'Portugal':4,'Russia':4,'Ukraine':4,'Netherlands':4,'Turkey':4,
        'Belgium':3,'Greece':3,'Scotland':3,'Austria':3,'Switzerland':3,
        'Denmark':3,'Czech':3,'Romania':3,'Israel':3,'Croatia':3}
def model_rating(club, apps, pos, years):
    # Role is based on actual league appearances, not the order of a source row.
    role=min(10,round(apps/4))
    prime=1 if 23<=years<=30 else (-1 if years<=19 else 0)
    keeper=1 if pos==0 and years>=25 else 0
    return max(52,min(83,52+2*int(club['rep'])+STRONG.get(club['country'],2)+role+prime+keeper))

def attributes(ovr,pos,identity):
    noise=lambda tag,n:stable(identity+tag,n)-n//2
    if pos==0:return max(35,ovr-17+noise('speed',7)),max(45,ovr+noise('stamina',7)),min(92,ovr+3+noise('quality',5))
    if pos==1:return max(45,ovr-2+noise('speed',9)),min(92,ovr+2+noise('stamina',7)),min(92,ovr+noise('quality',7))
    if pos==2:return max(45,ovr+noise('speed',9)),min(92,ovr+1+noise('stamina',7)),min(92,ovr+2+noise('quality',7))
    return min(94,ovr+2+noise('speed',9)),max(45,ovr-1+noise('stamina',7)),min(94,ovr+1+noise('quality',7))


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--old",type=Path,default=Path("overrides/app/src/main/assets/europe_world_v74.tsv"))
    ap.add_argument("--facts",type=Path,default=Path("tools/eurofotbal_roster_facts.tsv"))
    ap.add_argument("--supplement",type=Path)
    ap.add_argument("--clubs",type=Path,default=Path("overrides/app/src/main/assets/europe_clubs_v72.tsv"))
    ap.add_argument("--fifa",type=Path,default=Path("../fifa11-fut-source.csv"))
    ap.add_argument("--output",type=Path,default=Path("overrides/app/src/main/assets/europe_world_v75.tsv"))
    ap.add_argument("--audit",type=Path,default=Path("tools/v76_roster_audit.tsv"))
    ap.add_argument("--unmatched",type=Path,default=Path("tools/v76_unmatched.tsv"))
    args=ap.parse_args()
    old=read(args.old); facts=read(args.facts); clubs=read(args.clubs)
    if args.supplement:
        known={(f['club_id'],f['identity_key']) for f in facts}
        for f in read(args.supplement):
            if (f['club_id'],f['identity_key']) not in known:
                facts.append(f)
                known.add((f['club_id'],f['identity_key']))
    owners={key(x['player']):x['league']+':'+x['clubIndex'] for x in old if x['type']=='P'}
    topfive={key(x['player']) for x in read(Path('overrides/nationalities_v42.tsv'))}
    by_fact=defaultdict(list)
    for f in facts: by_fact[f['club_id']].append(f)
    by_club={c['id']:c for c in clubs}
    by_name={(c['country'],c['name']):c for c in clubs}
    fifa=defaultdict(list)
    if args.fifa.exists():
        with args.fifa.open(encoding='utf-8-sig',newline='') as f:
            for c in csv.DictReader(f):fifa[key(c['NAME'])].append(c)
    additions=Counter(); changes=Counter(); unmatched=[]; result=[];audit=[]
    groups=defaultdict(list)
    for x in old:
        if x['type']=='P':groups[(x['league'],x['clubIndex'])].append(x)
    for t in old:
        if t['type']!='T':continue
        c=by_name[(t['nationality'],t['club'])]; rows=[p for p in groups[(t['league'],t['clubIndex'])] if p['uid'] not in DUPLICATE_UIDS|DATE_CONFLICT_UIDS]
        available=by_fact[c['id']]; used=set()
        for p in rows:
            identity=key(p['player'])
            alias=EXPLICIT_ALIASES.get((c['id'],identity),identity)
            exact=[f for f in available if f['identity_key']==alias]
            if len(exact)==1: fact=exact[0]
            else:
                aliases=[f for f in available if f['identity_key'] not in used and identity_match(p['player'],f['player'])]
                if len(aliases)==1: fact=aliases[0]
                else:
                    # Whole-name similarity can mistake two different surnames
                    # (e.g. Steven Smith / Steven Naismith) for one player.
                    fact=None
            if fact and fact['identity_key'] not in used:
                used.add(fact['identity_key'])
                pos={'GK':0,'DEF':1,'MID':2,'ATT':3}[fact['position']]
                if int(p['position'])!=pos:changes['position']+=1
                p['position']=str(pos)
                a=age(fact['dob'],c['country'] in {'Russia','Norway','Sweden','Finland','Ireland','Belarus'})
                if 16<=a<=45:
                    p['age']=str(a); changes['age']+=1
                appearances=int(fact['appearances']) if fact['appearances'].isdigit() else None
                model=model_rating(c,appearances,pos,int(p['age'])) if appearances is not None else None
                if model is not None and 'FIFA11' not in p['provenance'] and int(p['overall'])!=model:
                    p['overall']=str(model);changes['rating_model']+=1
                if appearances is None:
                    p['provenance']='SEASON_ROSTER_FIFA11' if 'FIFA11' in p['provenance'] else 'SEASON_ROSTER_EST_RATING'
                else:
                    p['provenance']='SEASON_APPS_FIFA11' if 'FIFA11' in p['provenance'] else 'SEASON_APPS_EST_RATING'
            else:
                fact=None
                unmatched.append((c['name'],p['player']));p['provenance']='UNVERIFIED_'+p['provenance']
            cards=fifa.get(identity,[])
            # A one-letter transliteration variant at the same club is safe;
            # FUT duplicate boosted cards are *not* independent observations.
            if not cards and fact:
                cards=fifa.get(fact['identity_key'],[])
            if cards and 'FIFA11' in p['provenance']:
                base=min(int(x['RATING']) for x in cards)
                p['overall']=str(max(int(p['overall']),base))
            if c['id']=='eu_russia_zenit-st-petersburg' and identity=='vyacheslavmalafeev':
                p['overall']='78';p['position']='0';p['provenance']='SOFIFA11_SEASON_APPS'
            if c['id']=='eu_russia_zenit-st-petersburg' and identity=='aleksandranyukov':
                p['overall']='80';p['position']='1';p['provenance']='FIFA11_ALIAS_SEASON_APPS'
            if c['id']=='eu_russia_zenit-st-petersburg' and identity=='aleksandrkerzhakov':
                p['overall']='78';p['position']='3';p['provenance']='FIFA11_ALIAS_SEASON_APPS'
            if c['id']=='eu_portugal_sl-benfica' and identity=='maxipereira':
                # UEFA's 2010/11 match reports identify him as Benfica's right-back.
                p['position']='1';p['provenance']='SEASON_APPS_UEFA11_ROLE'
            ovr=int(p['overall']);spe,res,qua=attributes(ovr,int(p['position']),identity);p['speed']=str(spe);p['resistance']=str(res);p['quality']=str(qua);p['value']=str(max(250000,(ovr-50)**2*9000));p['wage']=str(max(50000,(int(p['value'])//18//10000)*10000))
            audit.append(dict(club=c['name'],player=p['player'],status=('SEASON_APPS_CONFIRMED' if fact['appearances'].isdigit() else 'SEASON_ROSTER_CONFIRMED') if fact else 'UNVERIFIED_SOURCE_GAP',
                              appearances=fact['appearances'] if fact else '',source=fact['source_url'] if fact else '',
                              position=p['position'],age=p['age'],overall=p['overall'],provenance=p['provenance']))
        existing={key(p['player']) for p in rows}
        # Guarantee two real keepers where the archive supports them.
        keepers=sorted((f for f in available if f['position']=='GK'),key=lambda f:int(f['appearances']) if f['appearances'].isdigit() else 0,reverse=True)
        targets=[]
        for f in keepers:
            if sum(p['position']=='0' for p in rows)+sum(z['position']=='GK' for z in targets)>=2:break
            targets.append(f)
        # Restore regular first-team players omitted from the short research
        # draft; no 0-appearance academy padding and no cross-club duplicates.
        regulars=sorted((f for f in available if f['position']!='GK' and f['appearances'].isdigit() and int(f['appearances'])>=18),key=lambda f:int(f['appearances']),reverse=True)
        targets.extend(regulars)
        for f in targets:
            identity=f['identity_key']
            if identity in used or identity in existing or identity in topfive or identity in owners or any(identity_match(f['player'],p['player']) for p in rows):continue
            if len(rows)>=26:break
            pos={'GK':0,'DEF':1,'MID':2,'ATT':3}[f['position']]
            if pos==0 and sum(p['position']=='0' for p in rows)>=2:continue
            if pos!=0 and sum(p['position']==str(pos) for p in rows)>=({1:9,2:10,3:7}[pos]):continue
            a=age(f['dob'],c['country'] in {'Russia','Norway','Sweden','Finland','Ireland','Belarus'})
            if a<16 or a>45:continue
            apps=int(f['appearances']) if f['appearances'].isdigit() else 0;ovr=model_rating(c,apps,pos,a)
            cards=fifa.get(identity,[])
            if cards:ovr=max(ovr,min(int(card['RATING']) for card in cards))
            val=max(250000,(ovr-50)**2*9000)
            uid='eu:'+identity+':'+f['dob'].replace('.','')
            spe,res,qua=attributes(ovr,pos,identity)
            p=dict(type='P',league=t['league'],clubIndex=t['clubIndex'],club=t['club'],playerIndex=str(len(rows)),player=f['player'],position=str(pos),age=str(a),overall=str(ovr),nationality='Unknown',speed=str(spe),resistance=str(res),quality=str(qua),morale='55',style='0',formation='0',value=str(val),wage=str(max(50000,(val//18//10000)*10000)),uid=uid,provenance='SEASON_ARCHIVE_EST_RATING')
            rows.append(p);owners[identity]=t['league']+':'+t['clubIndex'];existing.add(identity);additions['GK' if pos==0 else 'outfield']+=1
            audit.append(dict(club=c['name'],player=p['player'],status='SEASON_ROSTER_ADDED' if not f['appearances'].isdigit() else 'SEASON_APPS_ADDED',appearances=f['appearances'],source=f['source_url'],position=p['position'],age=p['age'],overall=p['overall'],provenance=p['provenance']))
        if not any(p['position']=='0' for p in rows):raise SystemExit('No verified goalkeeper: '+c['name'])
        if len(rows)>30:raise SystemExit('Oversized roster: '+c['name'])
        result.append(t)
        for i,p in enumerate(rows):p['playerIndex']=str(i);result.append(p)
    fields=list(old[0]);args.output.parent.mkdir(parents=True,exist_ok=True)
    with args.output.open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(result)
    print('players',sum(x['type']=='P' for x in result),'additions',dict(additions),'changes',dict(changes),'unmatched',len(unmatched))
    print('unmatched examples',unmatched[:20])
    with args.unmatched.open('w',encoding='utf-8',newline='') as f:
        w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(['club','player']);w.writerows(unmatched)
    with args.audit.open('w',encoding='utf-8',newline='') as f:
        fields=['club','player','status','appearances','source','position','age','overall','provenance']
        w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(audit)


if __name__=='__main__':main()
